/**
 * Five-language interface labels for the Phase 2 locations (M08–M14). These are
 * control/label strings only — never narration, dialogue, religious text, song
 * or message content (all of that comes from the Sheet). The Sheet stays first:
 * the runtime resolves `world_<key>` from `08_UI_TEXT` and only falls back to
 * these values, which `scripts/seed-phase2-config.mjs` can register once so
 * Ahmed can edit them without a rebuild.
 *
 * Order in every tuple: en, ar-EG, it, el, fr (same as 07_LANGUAGES).
 * Proper names whose localization the Living Bible still lists as Open
 * (Sunberry Fields, The Everkeep) and fixed names (VARcade, Vinyl Café,
 * Veoulla's Cottage) are shown unchanged in every language.
 */
export type WorldLabel = readonly [string, string, string, string, string];

export const WORLD_UI_TEXT = {
  /* generic */
  close: ['Close', 'اقفلي', 'Chiudi', 'Κλείσιμο', 'Fermer'],
  back: ['Back', 'رجوع', 'Indietro', 'Πίσω', 'Retour'],
  continue: ['Continue', 'كمّلي', 'Continua', 'Συνέχεια', 'Continuer'],
  enter: ['Enter', 'ادخلي', 'Entra', 'Είσοδος', 'Entrer'],
  leave: ['Leave', 'اخرجي', 'Esci', 'Έξοδος', 'Sortir'],
  walk_on: ['Walk on', 'كمّلي طريقك', 'Prosegui', 'Προχώρα', 'Continuer la route'],
  temporary_visual: [
    'Temporary visual — artwork pending',
    'صورة مؤقتة — الرسمة لسه جاية',
    'Immagine provvisoria — illustrazione in arrivo',
    'Προσωρινή εικόνα — η εικονογράφηση έρχεται',
    'Visuel provisoire — illustration à venir',
  ],
  not_available_yet: [
    'Nothing here yet.',
    'مفيش حاجة هنا لسه.',
    'Ancora nulla qui.',
    'Τίποτα ακόμα εδώ.',
    'Rien ici pour l’instant.',
  ],
  content_pending: [
    'This is still being prepared.',
    'دي لسه بتتجهز.',
    'Questo è ancora in preparazione.',
    'Αυτό ετοιμάζεται ακόμα.',
    'Ceci est encore en préparation.',
  ],
  cafe_story_locked: [
    'The gramophone will wake once you have finished your first visit to the Church.',
    'الجرامافون هيصحى لما تخلصي زيارتك الأولى للكنيسة.',
    'Il grammofono si risveglierà quando avrai finito la tua prima visita in chiesa.',
    'Το γραμμόφωνο θα ξυπνήσει όταν ολοκληρώσεις την πρώτη σου επίσκεψη στην εκκλησία.',
    'Le gramophone se réveillera quand tu auras terminé ta première visite à l’église.',
  ],
  arcade_story_locked: [
    'The VARcade opens after the Vinyl Café.',
    'الـ VARcade هيفتح بعد الكافيه.',
    'Il VARcade apre dopo il Vinyl Café.',
    'Το VARcade ανοίγει μετά το Vinyl Café.',
    'Le VARcade ouvre après le Vinyl Café.',
  ],
  ocean_look: [
    'Look out at the ocean',
    'بصي على المحيط',
    'Guarda l’oceano',
    'Κοίτα τον ωκεανό',
    'Regarde l’océan',
  ],
  ocean_loading: [
    'The ocean is coming into view…',
    'المحيط بيظهر…',
    'L’oceano sta arrivando…',
    'Ο ωκεανός εμφανίζεται…',
    'L’océan apparaît…',
  ],
  ocean_unavailable: [
    'The ocean view is not ready yet.',
    'منظر المحيط لسه مش جاهز.',
    'La vista sull’oceano non è ancora pronta.',
    'Η θέα στον ωκεανό δεν είναι έτοιμη ακόμα.',
    'La vue sur l’océan n’est pas encore prête.',
  ],
  ocean_restricted: [
    'This video cannot be played here right now.',
    'الفيديو ده مينفعش يتشغل هنا دلوقتي.',
    'Questo video non può essere riprodotto qui in questo momento.',
    'Αυτό το βίντεο δεν μπορεί να αναπαραχθεί εδώ αυτή τη στιγμή.',
    'Cette vidéo ne peut pas être lue ici pour le moment.',
  ],
  walkman_open: [
    'Open the Walkman',
    'افتحي الووكمان',
    'Apri il Walkman',
    'Άνοιξε το Walkman',
    'Ouvre le Walkman',
  ],
  walkman_playlist: ['Playlist', 'قائمة التشغيل', 'Playlist', 'Λίστα', 'Liste de lecture'],
  walkman_prev: [
    'Previous track',
    'الأغنية السابقة',
    'Brano precedente',
    'Προηγούμενο',
    'Piste précédente',
  ],
  walkman_next: ['Next track', 'الأغنية التالية', 'Brano successivo', 'Επόμενο', 'Piste suivante'],
  walkman_shuffle: ['Shuffle', 'عشوائي', 'Casuale', 'Τυχαία σειρά', 'Aléatoire'],
  walkman_repeat_off: [
    'Repeat: off',
    'التكرار: متوقف',
    'Ripeti: no',
    'Επανάληψη: όχι',
    'Répéter : non',
  ],
  walkman_repeat_all: [
    'Repeat: playlist',
    'التكرار: القائمة كلها',
    'Ripeti: playlist',
    'Επανάληψη: λίστα',
    'Répéter : la liste',
  ],
  walkman_repeat_one: [
    'Repeat: this track',
    'التكرار: الأغنية دي',
    'Ripeti: questo brano',
    'Επανάληψη: αυτό το κομμάτι',
    'Répéter : cette piste',
  ],
  walkman_volume: ['Volume', 'مستوى الصوت', 'Volume', 'Ένταση', 'Volume'],
  walkman_mute: ['Mute', 'كتم الصوت', 'Silenzia', 'Σίγαση', 'Couper le son'],
  walkman_unmute: ['Unmute', 'إلغاء الكتم', 'Riattiva audio', 'Επαναφορά ήχου', 'Rétablir le son'],
  walkman_seek: [
    'Position in the song',
    'مكان في الأغنية',
    'Posizione nel brano',
    'Θέση στο τραγούδι',
    'Position dans la chanson',
  ],
  walkman_empty: [
    'No songs are on your Walkman yet. Visit the Vinyl Café to find some.',
    'مفيش أغاني على الووكمان لسه. زوري Vinyl Café عشان تلاقي.',
    'Nessun brano sul Walkman. Passa al Vinyl Café per trovarne.',
    'Δεν υπάρχουν τραγούδια στο Walkman ακόμα. Πήγαινε στο Vinyl Café.',
    'Aucune chanson sur ton Walkman. Passe au Vinyl Café pour en trouver.',
  ],
  church_candle_corner: [
    'The candle corner',
    'ركن الشموع',
    'L’angolo delle candele',
    'Η γωνιά των κεριών',
    'Le coin des bougies',
  ],
  church_extinguish_candle: [
    'Put out the candle',
    'اطفي الشمعة',
    'Spegni la candela',
    'Σβήσε το κερί',
    'Éteins la bougie',
  ],
  church_candle_stays_lit: [
    'This candle stays lit for today’s occasion.',
    'الشمعة دي هتفضل منورة علشان مناسبة النهارده.',
    'Questa candela resta accesa per l’occasione di oggi.',
    'Αυτό το κερί μένει αναμμένο για τη σημερινή περίσταση.',
    'Cette bougie reste allumée pour l’occasion du jour.',
  ],
  church_add_candle: [
    'Add candle',
    'ضيفي شمعة',
    'Aggiungi candela',
    'Πρόσθεσε κερί',
    'Ajouter une bougie',
  ],
  church_remove_candle: [
    'Remove selected candle',
    'شيلي الشمعة المحددة',
    'Rimuovi la candela selezionata',
    'Αφαίρεσε το επιλεγμένο κερί',
    'Retirer la bougie sélectionnée',
  ],
  church_select_candle: [
    'Select this candle',
    'حددي الشمعة دي',
    'Seleziona questa candela',
    'Επίλεξε αυτό το κερί',
    'Sélectionner cette bougie',
  ],
  church_candle_selected: ['Selected', 'متحددة', 'Selezionata', 'Επιλεγμένο', 'Sélectionnée'],
  church_tray_full: [
    'The candle tray is full.',
    'صينية الشموع مليانة.',
    'Il vassoio delle candele è pieno.',
    'Ο δίσκος με τα κεριά είναι γεμάτος.',
    'Le plateau à bougies est plein.',
  ],
  arcade_game_untitled: ['Game', 'لعبة', 'Gioco', 'Παιχνίδι', 'Jeu'],
  arcade_locked_cost: [
    'Locked · costs {n}',
    'مقفولة · بـ {n}',
    'Bloccata · costa {n}',
    'Κλειδωμένη · κοστίζει {n}',
    'Verrouillée · coûte {n}',
  ],
  museum_exhibit_untitled: ['Exhibit', 'معروض', 'Esposizione', 'Έκθεμα', 'Pièce'],
  museum_wing_untitled: ['Wing', 'جناح', 'Ala', 'Πτέρυγα', 'Aile'],
  museum_exhibit_locked: [
    'Not opened yet',
    'لسه ما اتفتحش',
    'Non ancora aperto',
    'Δεν έχει ανοίξει ακόμα',
    'Pas encore ouvert',
  ],
  load_failed: [
    'This could not be loaded.',
    'مقدرناش نحمّل ده.',
    'Non è stato possibile caricarlo.',
    'Δεν φορτώθηκε.',
    'Le chargement a échoué.',
  ],
  farm_plant_here: ['Plant here', 'ازرعي هنا', 'Pianta qui', 'Φύτεψε εδώ', 'Planter ici'],
  place_junction: ['The crossroads', 'مفترق الطريق', 'Il bivio', 'Η διασταύρωση', 'Le carrefour'],
  junction_ahead: [
    'Continue along the road ahead',
    'كمّلي على الطريق قدامك',
    'Prosegui lungo la strada',
    'Συνέχισε στον δρόμο μπροστά',
    'Continuer sur la route devant',
  ],
  junction_left_church: [
    'Church, on the left',
    'الكنيسة على الشمال',
    'La chiesa, a sinistra',
    'Η εκκλησία, αριστερά',
    'L’église, à gauche',
  ],
  junction_right_cafe: [
    'Vinyl Café, on the right',
    'Vinyl Café على اليمين',
    'Vinyl Café, a destra',
    'Vinyl Café, δεξιά',
    'Vinyl Café, à droite',
  ],
  junction_locked_church: [
    'The Church is not open yet.',
    'الكنيسة لسه مقفولة.',
    'La chiesa non è ancora aperta.',
    'Η εκκλησία δεν είναι ακόμα ανοιχτή.',
    'L’église n’est pas encore ouverte.',
  ],
  junction_locked_cafe: [
    'The Vinyl Café will open once you have finished at the Church.',
    'الكافيه هيفتح لما تخلصي في الكنيسة.',
    'Il Vinyl Café aprirà quando avrai finito in chiesa.',
    'Το Vinyl Café θα ανοίξει όταν τελειώσεις στην εκκλησία.',
    'Le Vinyl Café ouvrira quand tu auras terminé à l’église.',
  ],
  junction_locked_ahead: [
    'The road ahead opens after the Vinyl Café.',
    'الطريق قدامك هيفتح بعد الكافيه.',
    'La strada avanti si apre dopo il Vinyl Café.',
    'Ο δρόμος μπροστά ανοίγει μετά το Vinyl Café.',
    'La route devant s’ouvre après le Vinyl Café.',
  ],
  gender_legend: ['Gender', 'النوع', 'Genere', 'Φύλο', 'Genre'],
  gender_male: ['Male', 'ذكر', 'Maschio', 'Αρσενικό', 'Mâle'],
  gender_female: ['Female', 'أنثى', 'Femmina', 'Θηλυκό', 'Femelle'],
  gender_required: [
    'Please choose Male or Female.',
    'اختاري ذكر أو أنثى.',
    'Scegli Maschio o Femmina.',
    'Διάλεξε Αρσενικό ή Θηλυκό.',
    'Choisissez Mâle ou Femelle.',
  ],
  enable_audio: [
    'Tap to enable sound',
    'دوسي عشان الصوت يشتغل',
    'Tocca per attivare l’audio',
    'Πάτα για ήχο',
    'Touchez pour activer le son',
  ],
  church_mute_audio: [
    'Mute the reading',
    'اكتمي القراءة',
    'Disattiva la lettura',
    'Σίγαση της ανάγνωσης',
    'Couper la lecture',
  ],
  church_unmute_audio: [
    'Unmute the reading',
    'شغّلي القراءة تاني',
    'Riattiva la lettura',
    'Κατάργηση σίγασης ανάγνωσης',
    'Réactiver la lecture',
  ],
  keys: ['Keys', 'المفاتيح', 'Chiavi', 'Κλειδιά', 'Clés'],
  first_message_unavailable: [
    'The first message is not available for this player yet. Ask Ahmed to add its first-visit text, then retry. Your progress has not been advanced.',
    'أول رسالة لسه مش متاحة للاعب ده. خلي أحمد يضيف نص رسالة أول زيارة، وبعدها جرّبي تاني. تقدمك ما اتغيرش.',
    'Il primo messaggio non è disponibile. Chiedi ad Ahmed di aggiungere il testo della prima visita, poi riprova. I progressi non sono avanzati.',
    'Το πρώτο μήνυμα δεν είναι διαθέσιμο. Ζήτησε από τον Ahmed να προσθέσει το κείμενο πρώτης επίσκεψης και δοκίμασε ξανά. Η πρόοδος δεν προχώρησε.',
    'Le premier message est indisponible. Demande à Ahmed d’ajouter le texte de première visite, puis réessaie. La progression n’a pas avancé.',
  ],
  check_saved_reward: [
    'Check saved Arcade win',
    'راجعي فوز الأركيد المحفوظ',
    'Verifica la vittoria salvata',
    'Έλεγχος αποθηκευμένης νίκης',
    'Vérifier la victoire enregistrée',
  ],
  arcade_intro_required: [
    'Win the first Arcade game to earn its key, then return here.',
    'اكسبِي أول لعبة في الأركيد عشان تاخدي مفتاحها، وارجعي هنا.',
    'Vinci il primo gioco della sala per ottenere la chiave, poi torna qui.',
    'Κέρδισε το πρώτο παιχνίδι για το κλειδί και επέστρεψε εδώ.',
    'Gagne le premier jeu pour obtenir sa clé, puis reviens ici.',
  ],
  museum_key_help: [
    'The gate needs the listed keys. If an Arcade win was saved without its key, check it below. Achievements are not required for this gate.',
    'البوابة محتاجة المفاتيح اللي في القائمة. لو فوز الأركيد اتحفظ من غير مفتاحه، راجعيه تحت. البوابة دي مش محتاجة إنجازات.',
    'Servono le chiavi elencate. Verifica qui una vittoria salvata senza chiave. Questo cancello non richiede obiettivi.',
    'Χρειάζονται τα κλειδιά της λίστας. Έλεγξε μια νίκη χωρίς κλειδί παρακάτω. Δεν απαιτούνται επιτεύγματα.',
    'Il faut les clés indiquées. Vérifie une victoire enregistrée sans sa clé. Ce portail ne demande pas de succès.',
  ],
  reward_check_done: [
    'Saved reward checked. Seat the available keys below.',
    'راجعنا المكافأة المحفوظة. حطي المفاتيح المتاحة تحت.',
    'Ricompensa verificata. Inserisci le chiavi disponibili.',
    'Η ανταμοιβή ελέγχθηκε. Τοποθέτησε τα διαθέσιμα κλειδιά.',
    'Récompense vérifiée. Place les clés disponibles.',
  ],
  reward_unavailable: [
    'The configured reward is unavailable or its daily limit was reached. Ask Ahmed to check the reward setup, or retry on the next eligible day.',
    'المكافأة مش متاحة أو وصلتي للحد اليومي. خلي أحمد يراجع إعدادها، أو جرّبي في اليوم المتاح الجاي.',
    'La ricompensa non è disponibile o il limite giornaliero è raggiunto. Chiedi ad Ahmed di verificarla o riprova il prossimo giorno valido.',
    'Η ανταμοιβή δεν είναι διαθέσιμη ή ισχύει ημερήσιο όριο. Ζήτησε έλεγχο από τον Ahmed ή δοκίμασε την επόμενη διαθέσιμη ημέρα.',
    'Récompense indisponible ou limite quotidienne atteinte. Demande à Ahmed de vérifier sa configuration ou réessaie le prochain jour admissible.',
  ],
  /* achievements */
  achievements_title: ['Achievements', 'الإنجازات', 'Obiettivi', 'Επιτεύγματα', 'Succès'],
  achievements_open: [
    'Open achievements',
    'افتحي الإنجازات',
    'Apri gli obiettivi',
    'Άνοιξε τα επιτεύγματα',
    'Ouvrir les succès',
  ],
  achievements_empty: [
    'No achievements yet — keep exploring.',
    'لسه مفيش إنجازات — كمّلي استكشاف.',
    'Ancora nessun obiettivo — continua a esplorare.',
    'Ακόμα κανένα επίτευγμα — συνέχισε να εξερευνάς.',
    'Aucun succès pour l’instant — continue d’explorer.',
  ],
  achievement_locked: ['Locked', 'مقفول', 'Bloccato', 'Κλειδωμένο', 'Verrouillé'],
  achievement_secret: [
    'Secret achievement',
    'إنجاز سري',
    'Obiettivo segreto',
    'Μυστικό επίτευγμα',
    'Succès secret',
  ],
  achievement_unlocked_on: ['Unlocked', 'اتفتح', 'Sbloccato', 'Ξεκλειδώθηκε', 'Débloqué'],
  key_received: [
    'You found a key!',
    'لقيتي مفتاح!',
    'Hai trovato una chiave!',
    'Βρήκες ένα κλειδί!',
    'Tu as trouvé une clé !',
  ],
  saving_retry: [
    'Could not reach the island. Try again.',
    'مقدرناش نوصل للجزيرة. حاولي تاني.',
    'Impossibile raggiungere l’isola. Riprova.',
    'Δεν φτάσαμε στο νησί. Δοκίμασε ξανά.',
    'Impossible de joindre l’île. Réessayez.',
  ],
  working: ['Working…', 'ثواني…', 'Un momento…', 'Μια στιγμή…', 'Un instant…'],
  candle_unknown: [
    'Save not yet confirmed. Try again to check the saved tray before repeating this action.',
    'لسه مش متأكدين إن الحفظ تم. حاولي تاني عشان نراجع الصينية المحفوظة قبل ما نكرر الخطوة.',
    'Salvataggio non ancora confermato. Riprova per controllare il vassoio prima di ripetere l’azione.',
    'Η αποθήκευση δεν επιβεβαιώθηκε ακόμη. Δοκίμασε ξανά για έλεγχο πριν επαναληφθεί η ενέργεια.',
    'Enregistrement non confirmé. Réessayez pour vérifier le plateau avant de répéter cette action.',
  ],
  candle_saved_followup: [
    'Your candle change is saved. Try again to finish updating progress.',
    'تغيير الشمعة اتحفظ. حاولي تاني عشان نكمل تحديث التقدم.',
    'La modifica è salvata. Riprova per completare l’aggiornamento dei progressi.',
    'Η αλλαγή αποθηκεύτηκε. Δοκίμασε ξανά για να ολοκληρωθεί η ενημέρωση προόδου.',
    'La modification est enregistrée. Réessayez pour terminer la mise à jour de la progression.',
  ],
  candle_not_saved: [
    'The saved tray does not show this change. Try again to retry the same action.',
    'الصينية المحفوظة مش ظاهرة فيها الخطوة دي. حاولي تاني عشان نكرر نفس الخطوة.',
    'La modifica non risulta nel vassoio salvato. Riprova la stessa azione.',
    'Η αλλαγή δεν εμφανίζεται στον αποθηκευμένο δίσκο. Δοκίμασε ξανά την ίδια ενέργεια.',
    'Le plateau enregistré ne montre pas ce changement. Réessayez la même action.',
  ],
  candle_refresh_failed: [
    'Your candle change is saved. Progress could not be refreshed; try again to refresh it.',
    'تغيير الشمعة اتحفظ. مقدرناش نحدّث عرض التقدم؛ حاولي تاني لتحديثه.',
    'La modifica è salvata. Non è stato possibile aggiornare i progressi; riprova ad aggiornarli.',
    'Η αλλαγή αποθηκεύτηκε. Η προβολή προόδου δεν ανανεώθηκε· δοκίμασε ξανά.',
    'La modification est enregistrée. La progression n’a pas pu être actualisée ; réessayez.',
  ],
  try_again: ['Try again', 'حاولي تاني', 'Riprova', 'Δοκίμασε ξανά', 'Réessayer'],
  save_unconfirmed: [
    'We could not confirm that was saved. It is safe to try again.',
    'مقدرناش نتأكد إن ده اتحفظ. تقدري تحاولي تاني بأمان.',
    'Non siamo riusciti a confermare il salvataggio. Puoi riprovare senza problemi.',
    'Δεν μπορέσαμε να επιβεβαιώσουμε την αποθήκευση. Μπορείς να ξαναδοκιμάσεις με ασφάλεια.',
    'Nous n’avons pas pu confirmer l’enregistrement. Vous pouvez réessayer sans risque.',
  ],
  still_loading: [
    'Still loading — the island is slow right now.',
    'لسه بنحمّل — الجزيرة بطيئة دلوقتي.',
    'Caricamento in corso — l’isola è lenta in questo momento.',
    'Ακόμα φορτώνει — το νησί είναι αργό τώρα.',
    'Chargement en cours — l’île est lente en ce moment.',
  ],
  /* place names */
  place_beach: ['Marevi Cove', 'خليج ماريفي', 'Cala Marevi', 'Όρμος Μαρέβι', 'Crique de Marevi'],
  place_church: ['Church', 'الكنيسة', 'Chiesa', 'Εκκλησία', 'Église'],
  place_cafe: ['Vinyl Café', 'Vinyl Café', 'Vinyl Café', 'Vinyl Café', 'Vinyl Café'],
  place_arcade: ['VARcade', 'VARcade', 'VARcade', 'VARcade', 'VARcade'],
  place_cottage: [
    'Veoulla’s Cottage',
    'Veoulla’s Cottage',
    'Veoulla’s Cottage',
    'Veoulla’s Cottage',
    'Veoulla’s Cottage',
  ],
  place_farm: [
    'Sunberry Fields',
    'Sunberry Fields',
    'Sunberry Fields',
    'Sunberry Fields',
    'Sunberry Fields',
  ],
  place_museum: ['The Everkeep', 'The Everkeep', 'The Everkeep', 'The Everkeep', 'The Everkeep'],
  place_map: ['The Map', 'الخريطة', 'La mappa', 'Ο χάρτης', 'La carte'],
  /* church */
  church_candles: [
    'Candle corner',
    'ركن الشموع',
    'Angolo delle candele',
    'Γωνιά κεριών',
    'Coin des bougies',
  ],
  church_light_candle: [
    'Light a candle',
    'ولّعي شمعة',
    'Accendi una candela',
    'Άναψε ένα κερί',
    'Allume une bougie',
  ],
  church_verse: [
    'Verse of the day',
    'آية النهارده',
    'Versetto del giorno',
    'Εδάφιο της ημέρας',
    'Verset du jour',
  ],
  church_story: [
    'Bible story',
    'قصة من الكتاب المقدس',
    'Storia biblica',
    'Βιβλική ιστορία',
    'Histoire biblique',
  ],
  church_gallery: [
    'Story gallery',
    'معرض القصص',
    'Galleria delle storie',
    'Συλλογή ιστοριών',
    'Galerie des histoires',
  ],
  church_photo: [
    'Photo and story',
    'صورة وحكايتها',
    'Foto e storia',
    'Φωτογραφία και ιστορία',
    'Photo et histoire',
  ],
  church_hymns: ['Hymns', 'الترانيم', 'Inni', 'Ύμνοι', 'Hymnes'],
  church_quiz: ['Quiz', 'اختبار', 'Quiz', 'Κουίζ', 'Quiz'],
  church_sit: [
    'Sit in silence',
    'اقعدي في هدوء',
    'Siediti in silenzio',
    'Κάθισε σιωπηλά',
    'Assieds-toi en silence',
  ],
  church_read: ['Read', 'اقري', 'Leggi', 'Διάβασε', 'Lire'],
  church_open_story: [
    'Open today’s story',
    'افتحي قصة النهارده',
    'Apri la storia di oggi',
    'Άνοιξε τη σημερινή ιστορία',
    'Ouvre l’histoire du jour',
  ],
  church_play_hymn: [
    'Play hymn',
    'شغّلي الترنيمة',
    'Ascolta l’inno',
    'Παίξε τον ύμνο',
    'Jouer l’hymne',
  ],
  church_answer_correct: ['Correct!', 'صح!', 'Esatto!', 'Σωστά!', 'Exact !'],
  church_answer_wrong: [
    'Not quite — read the explanation and try again.',
    'مش بالظبط — اقري الشرح وحاولي تاني.',
    'Non proprio — leggi la spiegazione e riprova.',
    'Όχι ακριβώς — διάβασε την εξήγηση και δοκίμασε ξανά.',
    'Pas tout à fait — lis l’explication et réessaie.',
  ],
  church_true: ['True', 'صح', 'Vero', 'Σωστό', 'Vrai'],
  church_false: ['False', 'غلط', 'Falso', 'Λάθος', 'Faux'],
  church_quiz_done: [
    'Quiz complete',
    'خلّصتي الاختبار',
    'Quiz completato',
    'Το κουίζ ολοκληρώθηκε',
    'Quiz terminé',
  ],
  church_quiz_perfect: ['Perfect!', 'ممتاز من أول مرة!', 'Perfetto!', 'Τέλεια!', 'Parfait !'],
  church_reference: ['Reference', 'المرجع', 'Riferimento', 'Παραπομπή', 'Référence'],
  church_none_today: [
    'Nothing is scheduled for today.',
    'مفيش حاجة النهارده.',
    'Nulla in programma oggi.',
    'Τίποτα προγραμματισμένο σήμερα.',
    'Rien de prévu aujourd’hui.',
  ],
  /* cafe */
  cafe_gramophone: ['Gramophone', 'الجرامافون', 'Grammofono', 'Γραμμόφωνο', 'Gramophone'],
  cafe_today: ['Today', 'النهارده', 'Oggi', 'Σήμερα', 'Aujourd’hui'],
  cafe_first_visit: [
    'Welcome song',
    'أغنية الترحيب',
    'Canzone di benvenuto',
    'Τραγούδι καλωσορίσματος',
    'Chanson de bienvenue',
  ],
  cafe_play: ['Play', 'شغّلي', 'Riproduci', 'Αναπαραγωγή', 'Lecture'],
  cafe_pause: ['Pause', 'إيقاف', 'Pausa', 'Παύση', 'Pause'],
  cafe_to_walkman: [
    'Listen on the Walkman',
    'اسمعي على الووكمان',
    'Ascolta con il Walkman',
    'Άκου στο Walkman',
    'Écouter au Walkman',
  ],
  cafe_why: [
    'Why this song',
    'ليه الأغنية دي',
    'Perché questa canzone',
    'Γιατί αυτό το τραγούδι',
    'Pourquoi cette chanson',
  ],
  cafe_request: [
    'Request a song',
    'اطلبي أغنية',
    'Richiedi una canzone',
    'Ζήτησε ένα τραγούδι',
    'Demander une chanson',
  ],
  cafe_request_hint: [
    'Song and artist',
    'الأغنية والفنان',
    'Canzone e artista',
    'Τραγούδι και καλλιτέχνης',
    'Chanson et artiste',
  ],
  cafe_request_send: [
    'Send request',
    'ابعتي الطلب',
    'Invia richiesta',
    'Στείλε το αίτημα',
    'Envoyer la demande',
  ],
  cafe_request_sent: [
    'Sent for review.',
    'اتبعت للمراجعة.',
    'Inviata per la revisione.',
    'Στάλθηκε για έλεγχο.',
    'Envoyée pour examen.',
  ],
  cafe_no_songs: [
    'No songs yet.',
    'مفيش أغاني لسه.',
    'Ancora nessuna canzone.',
    'Καμία μελωδία ακόμα.',
    'Pas encore de chansons.',
  ],
  walkman: ['Walkman', 'الووكمان', 'Walkman', 'Walkman', 'Walkman'],
  walkman_nothing: [
    'Nothing playing',
    'مفيش حاجة شغالة',
    'Nessun brano',
    'Καμία αναπαραγωγή',
    'Aucune lecture',
  ],
  walkman_receive: [
    'VAR hands you the Walkman.',
    'VAR بتديكي الووكمان.',
    'VAR ti porge il Walkman.',
    'Η VAR σου δίνει το Walkman.',
    'VAR te tend le Walkman.',
  ],
  /* arcade */
  arcade_machines: ['Machines', 'الماكينات', 'Macchine', 'Μηχανές', 'Bornes'],
  arcade_locked: ['Locked', 'مقفولة', 'Bloccata', 'Κλειδωμένη', 'Verrouillée'],
  arcade_unlock: ['Unlock', 'افتحي', 'Sblocca', 'Ξεκλείδωσε', 'Débloquer'],
  arcade_cost: ['Cost', 'التكلفة', 'Costo', 'Κόστος', 'Coût'],
  arcade_not_enough: [
    'Not enough tokens yet.',
    'مفيش توكنز كفاية لسه.',
    'Non abbastanza gettoni.',
    'Δεν αρκούν τα μάρκες.',
    'Pas assez de jetons.',
  ],
  arcade_play: ['Play', 'العبي', 'Gioca', 'Παίξε', 'Jouer'],
  arcade_best: [
    'Personal best',
    'أحسن نتيجة',
    'Record personale',
    'Προσωπικό ρεκόρ',
    'Record personnel',
  ],
  arcade_attempts: ['Attempts', 'المحاولات', 'Tentativi', 'Προσπάθειες', 'Essais'],
  arcade_recent: ['Recent', 'آخر المحاولات', 'Recenti', 'Πρόσφατα', 'Récents'],
  arcade_scoreboard: [
    'Scoreboard',
    'لوحة النتائج',
    'Classifica',
    'Πίνακας βαθμολογίας',
    'Tableau des scores',
  ],
  arcade_empty_slot: [
    'Empty cabinet',
    'ماكينة فاضية',
    'Cabina vuota',
    'Άδεια μηχανή',
    'Borne vide',
  ],
  arcade_win: ['You won!', 'كسبتي!', 'Hai vinto!', 'Κέρδισες!', 'Gagné !'],
  arcade_lose: [
    'Not this time — try again!',
    'المرة دي لأ — حاولي تاني!',
    'Non stavolta — riprova!',
    'Όχι αυτή τη φορά — ξαναδοκίμασε!',
    'Pas cette fois — réessaie !',
  ],
  arcade_again: ['Play again', 'العبي تاني', 'Gioca ancora', 'Παίξε ξανά', 'Rejouer'],
  arcade_level: ['Level', 'المستوى', 'Livello', 'Επίπεδο', 'Niveau'],
  arcade_moves: ['Moves', 'الحركات', 'Mosse', 'Κινήσεις', 'Coups'],
  arcade_score: ['Score', 'النتيجة', 'Punteggio', 'Βαθμολογία', 'Score'],
  arcade_time: ['Time', 'الوقت', 'Tempo', 'Χρόνος', 'Temps'],
  arcade_hint: [
    'VAR: take your time — look closely!',
    'VAR: خدي وقتك — ركّزي كويس!',
    'VAR: prenditi il tempo — guarda bene!',
    'VAR: πάρε χρόνο — κοίτα προσεκτικά!',
    'VAR : prends ton temps — regarde bien !',
  ],
  arcade_sfx_only: [
    'Sound effects only',
    'مؤثرات صوتية بس',
    'Solo effetti sonori',
    'Μόνο ηχητικά εφέ',
    'Effets sonores seulement',
  ],
  trivia_answer: ['Answer', 'جاوبي', 'Rispondi', 'Απάντησε', 'Répondre'],
  trivia_correct: ['Correct!', 'إجابة صح!', 'Corretto!', 'Σωστό!', 'Correct !'],
  trivia_incorrect: ['Not quite', 'مش كده', 'Non proprio', 'Όχι ακριβώς', 'Pas tout à fait'],
  trivia_next: [
    'Next question',
    'السؤال اللي بعده',
    'Prossima domanda',
    'Επόμενη ερώτηση',
    'Question suivante',
  ],
  trivia_question_of: ['Question', 'سؤال', 'Domanda', 'Ερώτηση', 'Question'],
  companion_hint_label: ['Ask', 'اسأليه', 'Chiedi', 'Ρώτα', 'Demander'],
  companion_hint_none: [
    'Nothing new right now.',
    'مفيش حاجة جديدة دلوقتي.',
    'Niente di nuovo per ora.',
    'Τίποτα νέο προς το παρόν.',
    'Rien de nouveau pour le moment.',
  ],
  /* cottage */
  cottage_mailbox: [
    'Mailbox',
    'صندوق البريد',
    'Cassetta della posta',
    'Γραμματοκιβώτιο',
    'Boîte aux lettres',
  ],
  cottage_unread: ['Unread', 'جديدة', 'Da leggere', 'Αδιάβαστα', 'Non lus'],
  cottage_archive: ['Archive', 'الأرشيف', 'Archivio', 'Αρχείο', 'Archives'],
  cottage_open: ['Open', 'افتحي', 'Apri', 'Άνοιξε', 'Ouvrir'],
  cottage_from: ['From', 'من', 'Da', 'Από', 'De'],
  cottage_sender_arafa: ['Arafa', 'عرفة', 'Arafa', 'Arafa', 'Arafa'],
  cottage_translate: [
    'Read in another language',
    'اقريها بلغة تانية',
    'Leggi in un’altra lingua',
    'Διάβασε σε άλλη γλώσσα',
    'Lire dans une autre langue',
  ],
  cottage_original: [
    'Original language',
    'اللغة الأصلية',
    'Lingua originale',
    'Αρχική γλώσσα',
    'Langue d’origine',
  ],
  cottage_voice_note: [
    'Play voice note',
    'شغّلي الرسالة الصوتية',
    'Ascolta il messaggio vocale',
    'Παίξε το φωνητικό μήνυμα',
    'Écouter le message vocal',
  ],
  cottage_no_mail: [
    'No messages yet.',
    'مفيش رسايل لسه.',
    'Ancora nessun messaggio.',
    'Κανένα μήνυμα ακόμα.',
    'Pas encore de messages.',
  ],
  cottage_countdown: [
    'Countdown',
    'العد التنازلي',
    'Conto alla rovescia',
    'Αντίστροφη μέτρηση',
    'Compte à rebours',
  ],
  cottage_days: ['days', 'يوم', 'giorni', 'ημέρες', 'jours'],
  cottage_hours: ['hours', 'ساعة', 'ore', 'ώρες', 'heures'],
  cottage_minutes: ['minutes', 'دقيقة', 'minuti', 'λεπτά', 'minutes'],
  cottage_seconds: ['seconds', 'ثانية', 'secondi', 'δευτερόλεπτα', 'secondes'],
  cottage_memory_frame: [
    'A memory from',
    'ذكرى من',
    'Un ricordo del',
    'Μια ανάμνηση από',
    'Un souvenir du',
  ],
  cottage_decor: ['Decorations', 'الديكور', 'Decorazioni', 'Διακοσμήσεις', 'Décorations'],
  cottage_place: ['Place', 'حطّي', 'Posiziona', 'Τοποθέτησε', 'Placer'],
  cottage_clear: ['Take back', 'شيلي', 'Riprendi', 'Πάρε πίσω', 'Reprendre'],
  cottage_window: ['Window', 'الشباك', 'Finestra', 'Παράθυρο', 'Fenêtre'],
  cottage_var_place: [
    'VAR’s place',
    'مكان VAR',
    'Il posto di VAR',
    'Η θέση της VAR',
    'La place de VAR',
  ],
  cottage_marcelino_place: [
    'Marcelino’s place',
    'مكان مارسيلينو',
    'Il posto di Marcelino',
    'Η θέση του Marcelino',
    'La place de Marcelino',
  ],
  cottage_reading_corner: [
    'Reading and memory corner',
    'ركن القراءة والذكريات',
    'Angolo lettura e ricordi',
    'Γωνιά ανάγνωσης και αναμνήσεων',
    'Coin lecture et souvenirs',
  ],
  cottage_marcelino_arrives: [
    'Marcelino hurries out of the garden with his mailbag!',
    'مارسيلينو بيجري من الجنينة بشنطة البريد!',
    'Marcelino corre fuori dal giardino con la sua borsa!',
    'Ο Marcelino τρέχει από τον κήπο με την τσάντα του!',
    'Marcelino arrive du jardin avec sa sacoche !',
  ],
  cottage_marcelino_runs: [
    '…and scampers away.',
    '…وبيجري تاني.',
    '…e scappa via.',
    '…και τρέχει μακριά.',
    '…et détale.',
  ],
  cottage_marcelino_here: [
    'Marcelino is here',
    'مارسيلينو هنا',
    'Marcelino è qui',
    'Ο Marcelino είναι εδώ',
    'Marcelino est là',
  ],
  cottage_marcelino_away: [
    'Marcelino is out and about',
    'مارسيلينو بره',
    'Marcelino è in giro',
    'Ο Marcelino είναι έξω',
    'Marcelino est sorti',
  ],
  cottage_deliveries: ['Deliveries', 'التوصيلات', 'Consegne', 'Παραδόσεις', 'Livraisons'],
  /* farm */
  farm_plot: ['Plot', 'قطعة', 'Appezzamento', 'Χωράφι', 'Parcelle'],
  farm_plant: ['Plant', 'ازرعي', 'Pianta', 'Φύτεψε', 'Planter'],
  farm_water: ['Water', 'اسقي', 'Annaffia', 'Πότισε', 'Arroser'],
  farm_harvest: ['Harvest', 'احصدي', 'Raccogli', 'Μάζεψε', 'Récolter'],
  farm_seeds: ['Seeds', 'البذور', 'Semi', 'Σπόροι', 'Graines'],
  farm_produce: ['Harvest', 'المحصول', 'Raccolto', 'Σοδειά', 'Récolte'],
  farm_empty: ['Empty', 'فاضية', 'Vuoto', 'Άδειο', 'Vide'],
  farm_planted: ['Needs water', 'محتاجة مياه', 'Ha sete', 'Θέλει νερό', 'A soif'],
  farm_growing: ['Growing', 'بتكبر', 'In crescita', 'Μεγαλώνει', 'Pousse'],
  farm_ready: [
    'Ready to harvest',
    'جاهزة للحصاد',
    'Pronto da raccogliere',
    'Έτοιμο για συγκομιδή',
    'Prêt à récolter',
  ],
  farm_wilted: [
    'Wilted — water to recover',
    'دبلانة — اسقيها عشان تفوق',
    'Appassita — annaffia per riprendersi',
    'Μαραμένο — πότισε για να ανακάμψει',
    'Fanée — arrose pour la ranimer',
  ],
  farm_rain: [
    'It is raining — the plants drink it in.',
    'بتمطر — النباتات بتشرب.',
    'Piove — le piante bevono.',
    'Βρέχει — τα φυτά πίνουν.',
    'Il pleut — les plantes boivent.',
  ],
  farm_rain_watered: [
    'Rain watered your plants.',
    'المطرة سقت زرعك.',
    'La pioggia ha annaffiato le piante.',
    'Η βροχή πότισε τα φυτά.',
    'La pluie a arrosé tes plantes.',
  ],
  farm_barn: [
    'Barn (closed for now)',
    'الحظيرة (مقفولة دلوقتي)',
    'Fienile (chiuso per ora)',
    'Αχυρώνας (κλειστός προς το παρόν)',
    'Grange (fermée pour l’instant)',
  ],
  farm_crop_sunflower: ['Sunflower', 'عباد الشمس', 'Girasole', 'Ηλιοτρόπιο', 'Tournesol'],
  farm_crop_mango: ['Mango', 'مانجو', 'Mango', 'Μάνγκο', 'Mangue'],
  farm_crop_blueberry: ['Blueberry', 'توت أزرق', 'Mirtillo', 'Μύρτιλο', 'Myrtille'],
  farm_no_seeds: [
    'No seeds left.',
    'مفيش بذور.',
    'Nessun seme.',
    'Δεν έμειναν σπόροι.',
    'Plus de graines.',
  ],
  /* museum */
  museum_road_gate: [
    'The final road gate',
    'بوابة الطريق الأخير',
    'Il cancello dell’ultima strada',
    'Η πύλη του τελευταίου δρόμου',
    'La grille de la dernière route',
  ],
  museum_seat_keys: [
    'Seat your keys in the gate',
    'ركّبي مفاتيحك في البوابة',
    'Inserisci le chiavi nel cancello',
    'Τοποθέτησε τα κλειδιά στην πύλη',
    'Place tes clés dans la grille',
  ],
  museum_need_keys: [
    'The Everkeep needs more keys.',
    'الـEverkeep عايز مفاتيح أكتر.',
    'The Everkeep richiede più chiavi.',
    'Το Everkeep χρειάζεται περισσότερα κλειδιά.',
    'The Everkeep demande plus de clés.',
  ],
  museum_seated: ['Seated', 'اتركّب', 'Inserita', 'Τοποθετήθηκε', 'Placée'],
  museum_open_door: [
    'Open the door',
    'افتحي الباب',
    'Apri la porta',
    'Άνοιξε την πόρτα',
    'Ouvre la porte',
  ],
  museum_central_hall: [
    'Central Hall',
    'القاعة الرئيسية',
    'Sala centrale',
    'Κεντρική αίθουσα',
    'Salle centrale',
  ],
  museum_artifact: [
    'The mysterious artifact',
    'القطعة الغامضة',
    'Il misterioso manufatto',
    'Το μυστηριώδες αντικείμενο',
    'L’artefact mystérieux',
  ],
  museum_look: [
    'Look closely',
    'بصّي كويس',
    'Guarda da vicino',
    'Κοίταξε προσεκτικά',
    'Regarde de près',
  ],
  museum_progress: [
    'Your island so far',
    'جزيرتك لحد دلوقتي',
    'La tua isola finora',
    'Το νησί σου μέχρι τώρα',
    'Ton île jusqu’ici',
  ],
  museum_wing_locked: [
    'This wing is still closed.',
    'الجناح ده لسه مقفول.',
    'Quest’ala è ancora chiusa.',
    'Αυτή η πτέρυγα είναι ακόμα κλειστή.',
    'Cette aile est encore fermée.',
  ],
  museum_wings: ['Wings', 'الأجنحة', 'Ali', 'Πτέρυγες', 'Ailes'],
  museum_empty_slot: [
    'An empty place, waiting…',
    'مكان فاضي، مستني…',
    'Un posto vuoto, in attesa…',
    'Μια άδεια θέση, περιμένει…',
    'Une place vide, en attente…',
  ],
  museum_open_exhibit: ['Open', 'افتحي', 'Apri', 'Άνοιξε', 'Ouvrir'],
  museum_book_prev: [
    'Previous page',
    'الصفحة اللي فاتت',
    'Pagina precedente',
    'Προηγούμενη σελίδα',
    'Page précédente',
  ],
  museum_book_next: [
    'Next page',
    'الصفحة الجاية',
    'Pagina successiva',
    'Επόμενη σελίδα',
    'Page suivante',
  ],
  museum_book_missing: [
    'The book has not been placed here yet.',
    'الكتاب لسه ماتحطش هنا.',
    'Il libro non è ancora stato collocato qui.',
    'Το βιβλίο δεν έχει τοποθετηθεί ακόμα.',
    'Le livre n’a pas encore été placé ici.',
  ],
  museum_archive_missing: [
    'The archive has not been opened yet.',
    'الأرشيف لسه ماتفتحش.',
    'L’archivio non è ancora stato aperto.',
    'Το αρχείο δεν έχει ανοίξει ακόμα.',
    'L’archive n’est pas encore ouverte.',
  ],
  museum_archive_intro: [
    'An earlier version of this world lives on, kept just as it was.',
    'نسخة قديمة من العالم ده لسه موجودة، متحفوظة زي ما كانت.',
    'Una versione precedente di questo mondo vive ancora, conservata come era.',
    'Μια παλαιότερη εκδοχή αυτού του κόσμου ζει ακόμα, όπως ακριβώς ήταν.',
    'Une ancienne version de ce monde existe encore, gardée telle quelle.',
  ],
  museum_archive_open_link: [
    'Open original website',
    'افتحي الموقع الأصلي',
    'Apri il sito originale',
    'Άνοιξε την αρχική ιστοσελίδα',
    'Ouvrir le site original',
  ],
  /* map */
  map_here: ['You are here', 'إنتي هنا', 'Sei qui', 'Είσαι εδώ', 'Tu es ici'],
  map_locked: [
    'Hidden in mist',
    'مستخبية في الضباب',
    'Nascosto nella foschia',
    'Κρυμμένο στην ομίχλη',
    'Cachée dans la brume',
  ],
  map_go: ['Travel here', 'روحي هنا', 'Vai qui', 'Πήγαινε εδώ', 'S’y rendre'],
  map_open: [
    'Open the Map',
    'افتحي الخريطة',
    'Apri la mappa',
    'Άνοιξε τον χάρτη',
    'Ouvre la carte',
  ],
  map_receive: [
    'Receive the Map',
    'استلمي الخريطة',
    'Ricevi la mappa',
    'Πάρε τον χάρτη',
    'Reçois la carte',
  ],
  /* replay */
  replay_title: [
    'Replay the first journey?',
    'تعيدي الرحلة الأولى؟',
    'Rivivere il primo viaggio?',
    'Να ξαναζήσεις το πρώτο ταξίδι;',
    'Rejouer le premier voyage ?',
  ],
  replay_start: ['Replay', 'إعادة', 'Rivivi', 'Επανάληψη', 'Rejouer'],
  replay_skip: ['Skip', 'تخطّي', 'Salta', 'Παράλειψη', 'Passer'],
  /* birthday_2026 (M16 narrow scope) */
  birthday_invite: [
    'There’s a little surprise waiting for you… shall we go see it?',
    'فيه مفاجأة صغيرة مستنياكي… نروح نشوفها؟',
    'C’è una piccola sorpresa che ti aspetta… andiamo a vederla?',
    'Σε περιμένει μια μικρή έκπληξη… πάμε να τη δούμε;',
    'Une petite surprise t’attend… on va la voir ?',
  ],
  birthday_celebrate_now: [
    'Let’s celebrate',
    'يلا نحتفل',
    'Festeggiamo',
    'Ας γιορτάσουμε',
    'Célébrons',
  ],
  birthday_later: ['Later', 'بعد شوية', 'Più tardi', 'Αργότερα', 'Plus tard'],
  birthday_skip: ['Skip', 'تخطّي', 'Salta', 'Παράλειψη', 'Passer'],
  birthday_replay_countdown: [
    'Live the surprise moment',
    'عيشي لحظة المفاجأة',
    'Rivivi il momento della sorpresa',
    'Ζήσε ξανά τη στιγμή της έκπληξης',
    'Revis le moment de la surprise',
  ],
  birthday_replay_badge: [
    'Replay — not the live moment',
    'إعادة — مش اللحظة الحقيقية',
    'Replay — non è il momento reale',
    'Επανάληψη — όχι η πραγματική στιγμή',
    'Rediffusion — pas le moment réel',
  ],
  birthday_greeting: [
    'Happy birthday, sweet Veoulla 🤍',
    'كل سنة وإنتِ طيبة يا فيولا 🤍',
    'Buon compleanno, dolce Veoulla 🤍',
    'Χρόνια πολλά, γλυκιά Βεούλα 🤍',
    'Joyeux anniversaire, douce Veoulla 🤍',
  ],
  birthday_wish_prompt: [
    'Take a moment and make a wish… you don’t have to write it down.',
    'خدي لحظة واتمني أمنية… مش لازم تكتبيها.',
    'Prenditi un momento ed esprimi un desiderio… non devi scriverlo.',
    'Πάρε μια στιγμή και κάνε μια ευχή… δεν χρειάζεται να τη γράψεις.',
    'Prends un instant et fais un vœu… tu n’es pas obligée de l’écrire.',
  ],
  birthday_wish_placeholder: [
    'Your wish, just for you (optional)',
    'أمنيتك، بس ليكي (اختياري)',
    'Il tuo desiderio, solo per te (facoltativo)',
    'Η ευχή σου, μόνο για σένα (προαιρετικό)',
    'Ton vœu, rien que pour toi (facultatif)',
  ],
  birthday_wish_save: [
    'Save my wish',
    'احفظي أمنيتي',
    'Salva il mio desiderio',
    'Αποθήκευσε την ευχή μου',
    'Enregistrer mon vœu',
  ],
  birthday_wish_saved: [
    'Wish kept, just for you',
    'الأمنية اتحفظت، ليكي بس',
    'Desiderio custodito, solo per te',
    'Η ευχή φυλάχτηκε, μόνο για σένα',
    'Vœu gardé, rien que pour toi',
  ],
  birthday_extinguish_candle: [
    'Put out the candles',
    'اطفي الشمع',
    'Spegni le candele',
    'Σβήσε τα κεριά',
    'Éteins les bougies',
  ],
  birthday_letter_title: [
    'A letter from Ahmed',
    'رسالة من أحمد',
    'Una lettera da Ahmed',
    'Ένα γράμμα από τον Ahmed',
    'Une lettre d’Ahmed',
  ],
  birthday_gifts_intro: [
    'A little something to stay with you in your world 🤍',
    'حاجة صغيرة تفضل معاكي في عالمك 🤍',
    'Un piccolo pensiero che resta con te nel tuo mondo 🤍',
    'Κάτι μικρό που θα μείνει μαζί σου στον κόσμο σου 🤍',
    'Un petit quelque chose qui reste avec toi dans ton monde 🤍',
  ],
  birthday_gift_letter_label: ['The letter', 'الرسالة', 'La lettera', 'Το γράμμα', 'La lettre'],
  birthday_gift_decoration_label: [
    'A garden keepsake',
    'تذكار من الجنينة',
    'Un ricordo dal giardino',
    'Ένα ενθύμιο από τον κήπο',
    'Un souvenir du jardin',
  ],
  birthday_gift_achievement_label: [
    'A birthday achievement',
    'إنجاز عيد الميلاد',
    'Un obiettivo di compleanno',
    'Ένα επίτευγμα γενεθλίων',
    'Un succès d’anniversaire',
  ],
  birthday_gift_claim: [
    'Open your gifts',
    'افتحي هداياكي',
    'Apri i tuoi regali',
    'Άνοιξε τα δώρα σου',
    'Ouvre tes cadeaux',
  ],
  birthday_gift_claimed: [
    'Gifts kept safe for you',
    'الهدايا محفوظة ليكي',
    'Regali custoditi per te',
    'Τα δώρα φυλάγονται για σένα',
    'Cadeaux gardés pour toi',
  ],
  birthday_continue: ['Continue', 'كمّلي', 'Continua', 'Συνέχεια', 'Continuer'],
  birthday_complete: [
    'Thank you for celebrating with us',
    'شكرًا إنك احتفلتي معانا',
    'Grazie per aver festeggiato con noi',
    'Ευχαριστούμε που γιόρτασες μαζί μας',
    'Merci d’avoir célébré avec nous',
  ],
  birthday_replay_celebration: [
    'Watch the celebration again',
    'شوفي الاحتفال تاني',
    'Rivivi ancora la festa',
    'Δες ξανά τη γιορτή',
    'Revoir la célébration',
  ],
  birthday_seconds_label: [
    'seconds remaining',
    'ثانية متبقية',
    'secondi rimanenti',
    'δευτερόλεπτα απομένουν',
    'secondes restantes',
  ],
  birthday_letter_pending: [
    'Ahmed’s letter is still being prepared.',
    'رسالة أحمد لسه بتتجهز.',
    'La lettera di Ahmed è ancora in preparazione.',
    'Το γράμμα του Ahmed ετοιμάζεται ακόμα.',
    'La lettre d’Ahmed est encore en préparation.',
  ],
  birthday_entry_label: [
    'Birthday surprise',
    'مفاجأة عيد الميلاد',
    'Sorpresa di compleanno',
    'Έκπληξη γενεθλίων',
    'Surprise d’anniversaire',
  ],
  birthday_entry_replay_label: [
    'Birthday celebration',
    'احتفال عيد الميلاد',
    'Festa di compleanno',
    'Γιορτή γενεθλίων',
    'Célébration d’anniversaire',
  ],
  birthday_menu_intro: [
    'Celebrate again, or just relive the final countdown.',
    'احتفلي تاني، أو عيشي لحظة العد التنازلي بس.',
    'Festeggia di nuovo, oppure rivivi solo il conto alla rovescia finale.',
    'Γιόρτασε ξανά, ή ζήσε μόνο την τελική αντίστροφη μέτρηση.',
    'Célèbre à nouveau, ou revis juste le compte à rebours final.',
  ],
  birthday_replay_celebration_cta: [
    'Replay celebration',
    'نحتفل تاني',
    'Rivivi la festa',
    'Ξαναζήσε τη γιορτή',
    'Rejouer la célébration',
  ],
  birthday_replay_countdown_cta: [
    'Replay the final 20 seconds',
    'أعيدي آخر ٢٠ ثانية',
    'Rivivi gli ultimi 20 secondi',
    'Ξαναζήσε τα τελευταία 20 δευτερόλεπτα',
    'Revivre les 20 dernières secondes',
  ],
  birthday_gift_decoration_placed_hint: [
    'Find it waiting in your Cottage decorations.',
    'هتلاقيها مستنياكي في زينة الكوخ.',
    'La trovi ad aspettarti tra le decorazioni del Cottage.',
    'Θα τη βρεις στα διακοσμητικά του Cottage.',
    'Retrouve-le parmi les décorations du Cottage.',
  ],
} as const satisfies Record<string, WorldLabel>;

export type WorldTextKey = keyof typeof WORLD_UI_TEXT;
