import { TAB_NAMES, TAB_REGISTRY, isTableTab, type TabName } from '@veoullas-world/sheet-schema';
import { headerFor, row } from './row-builder.js';

export type RawWorkbook = Record<TabName, string[][]>;

const LOCATION_SCENE: Record<string, string> = {
  gate: 'scene_gate_closed',
  beach: 'scene_beach_arrival',
  church: 'scene_church_approach',
  cafe: 'scene_cafe_approach',
  arcade: 'scene_arcade_approach',
  cottage: 'scene_cottage_approach',
  farm: 'scene_farm_approach',
  museum: 'scene_museum_approach',
};

function buildStoryBeats(): string[][] {
  const beatLocations = [
    'gate',
    'gate',
    'gate',
    'beach',
    'beach',
    'church',
    'cafe',
    'arcade',
    'cottage',
    'cottage',
    'farm',
    'museum',
    'museum',
    'museum',
    'museum',
    'museum',
    'museum',
    'museum',
  ];

  return beatLocations.map((location, i) => {
    const sequence = i + 1;
    const beatId = `beat_${String(sequence).padStart(2, '0')}`;
    const nextBeatId =
      i + 1 < beatLocations.length ? `beat_${String(sequence + 1).padStart(2, '0')}` : '';
    return row('14_STORY_BEATS', {
      beat_id: beatId,
      route_id: 'first_journey',
      sequence: String(sequence),
      scene_id: LOCATION_SCENE[location]!,
      location_id: location,
      beat_type: 'story',
      title_text_id: `${beatId}_title`,
      dialogue_group_id: `dlg_${beatId}`,
      voiceover_group_id: `vo_${beatId}`,
      required_interaction_id: '',
      reward_rule_id: '',
      checkpoint: sequence % 3 === 0 ? 'TRUE' : 'FALSE',
      next_beat_id: nextBeatId,
      map_locked: 'TRUE',
      walkman_state: 'locked',
      enabled: 'TRUE',
    });
  });
}

function buildDataDictionary(): string[][] {
  return TAB_NAMES.map((name) => {
    const def = TAB_REGISTRY[name];
    const primaryKey = isTableTab(def) ? (def.primaryKey ?? 'list_value_key') : 'n/a';
    return [
      name,
      def.purpose,
      primaryKey,
      def.readBy,
      def.writeBy,
      def.adminEditable ? 'TRUE' : 'FALSE',
      def.sensitivity,
      def.notes ?? '',
    ];
  });
}

const VALIDATION_LISTS_HEADER = ['list_name', 'value', 'sort_order', 'enabled', 'notes'];
const VALIDATION_LISTS_ROWS: string[][] = [
  ['boolean_text', 'TRUE', '1', 'TRUE', ''],
  ['boolean_text', 'FALSE', '2', 'TRUE', ''],
  ['boolean_int', '0', '1', 'TRUE', ''],
  ['boolean_int', '1', '2', 'TRUE', ''],
  ['role', 'owner', '1', 'TRUE', ''],
  ['role', 'admin', '2', 'TRUE', ''],
  ['role', 'guest', '3', 'FALSE', 'Not currently enabled'],
  ['direction', 'ltr', '1', 'TRUE', ''],
  ['direction', 'rtl', '2', 'TRUE', ''],
  ['locale', 'en', '1', 'TRUE', ''],
  ['locale', 'ar-EG', '2', 'TRUE', ''],
  ['locale', 'it', '3', 'TRUE', ''],
  ['locale', 'el', '4', 'TRUE', ''],
  ['locale', 'fr', '5', 'TRUE', ''],
  ['progress_status', 'not_started', '1', 'TRUE', ''],
  ['progress_status', 'active', '2', 'TRUE', ''],
  ['progress_status', 'completed', '3', 'TRUE', ''],
  ['session_status', 'active', '1', 'TRUE', ''],
  ['session_status', 'expired', '2', 'TRUE', ''],
  ['session_status', 'terminated', '3', 'TRUE', ''],
  ['message_read_status', 'unread', '1', 'TRUE', ''],
  ['message_read_status', 'read', '2', 'TRUE', ''],
  ['message_read_status', 'archived', '3', 'TRUE', ''],
  ['farm_state', 'empty', '1', 'TRUE', ''],
  ['farm_state', 'planted', '2', 'TRUE', ''],
  ['farm_state', 'growing', '3', 'TRUE', ''],
  ['farm_state', 'wilted', '4', 'TRUE', ''],
  ['farm_state', 'ready', '5', 'TRUE', ''],
  ['review_status', 'draft', '1', 'TRUE', ''],
  ['review_status', 'pending_review', '2', 'TRUE', ''],
  ['review_status', 'approved', '3', 'TRUE', ''],
  ['review_status', 'rejected', '4', 'TRUE', ''],
  ['location', 'gate', '1', 'TRUE', ''],
  ['location', 'beach', '2', 'TRUE', ''],
  ['location', 'church', '3', 'TRUE', ''],
  ['location', 'cafe', '4', 'TRUE', ''],
  ['location', 'arcade', '5', 'TRUE', ''],
  ['location', 'cottage', '6', 'TRUE', ''],
  ['location', 'farm', '7', 'TRUE', ''],
  ['location', 'museum', '8', 'TRUE', ''],
  ['location', 'map', '9', 'TRUE', ''],
  ['storage_provider', 'google_drive', '1', 'TRUE', 'Approved media provider'],
  ['var_speaker', 'user', '1', 'TRUE', ''],
  ['var_speaker', 'var', '2', 'TRUE', ''],
  ['var_speaker', 'system', '3', 'TRUE', ''],
  ['memory_category', 'preference', '1', 'TRUE', ''],
  ['memory_category', 'place', '2', 'TRUE', ''],
  ['memory_category', 'choice', '3', 'TRUE', ''],
  ['memory_category', 'achievement', '4', 'TRUE', ''],
  ['memory_category', 'mood', '5', 'TRUE', ''],
  ['memory_category', 'relationship', '6', 'TRUE', ''],
];

const README_ROWS: string[][] = [
  ["Veoulla's World — Google Sheets Data Blueprint (fixture)"],
  [],
  [
    'Prototype architecture • Sheets = authoritative data • Google Drive = media • Gemini API = VAR intelligence',
  ],
  [],
  [
    'Workbook version',
    '0.2',
    'Status',
    'Blueprint',
    'Languages',
    '5',
    'Target timezone',
    'Africa/Cairo',
    'Birthday',
    '2026-09-26',
  ],
  [],
  [
    'Locations',
    '',
    'Story beats',
    '',
    'Key inventory',
    '',
    'Unread messages',
    '',
    'Configured events',
  ],
  ['8', '', '18', '', '0', '', '1', '', '1'],
  [],
  ['Operating rules'],
  ['1', 'All world content/configuration and player state are Sheet-authoritative.'],
  ['2', 'The React frontend reads/writes only through backend endpoints.'],
  [],
  ['Tab catalog — see 38_DATA_DICTIONARY for complete ownership and integration notes'],
  ...TAB_NAMES.map((name, i) => [String(i + 1), name, TAB_REGISTRY[name].purpose]),
];

export const GOOD_WORKBOOK: RawWorkbook = {
  '00_README': README_ROWS,
  '01_APP_CONFIG': [
    headerFor('01_APP_CONFIG'),
    row('01_APP_CONFIG', {
      config_key: 'app_name',
      value: "Veoulla's World (Fixture)",
      value_type: 'text',
      description: 'Public world title',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'default_language',
      value: 'en',
      value_type: 'locale',
      description: 'Initial language on first open',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'supported_languages',
      value: 'en,ar-EG,it,el,fr',
      value_type: 'csv',
      description: 'Enabled locales',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'authoritative_time_zone',
      value: 'Africa/Cairo',
      value_type: 'timezone',
      description: 'Default event timezone',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'normal_start_location',
      value: 'cottage',
      value_type: 'location_id',
      description: 'Start location after first journey',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'sheet_refresh_seconds',
      value: '60',
      value_type: 'integer',
      description: 'Client configuration refresh interval',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'voiceover_enabled',
      value: 'TRUE',
      value_type: 'boolean',
      description: 'Master voice-over switch',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'real_weather_enabled',
      value: 'TRUE',
      value_type: 'boolean',
      description: 'Enable real + scheduled weather',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'admin_time_override_enabled',
      value: 'FALSE',
      value_type: 'boolean',
      description: 'Use Admin simulated time',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'current_story_version',
      value: 'first_journey_v1',
      value_type: 'id',
      description: 'Active story content version',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'current_event_id',
      value: 'birthday_2026',
      value_type: 'event_id',
      description: 'Primary configured event',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'media_provider',
      value: 'google_drive',
      value_type: 'text',
      description: 'Approved media origin; Firebase Storage is disabled',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'drive_root_folder_id',
      value: 'fixture_drive_root_folder_id',
      value_type: 'drive_folder_id',
      description: 'Root of Veoullas World Assets',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
    row('01_APP_CONFIG', {
      config_key: 'gemini_model',
      value: '<SET_GEMINI_MODEL_ID>',
      value_type: 'model_id',
      description: 'Active Gemini model for optional VAR conversation',
      enabled: 'TRUE',
      restart_required: 'FALSE',
    }),
  ],
  '02_USERS': [
    headerFor('02_USERS'),
    row('02_USERS', {
      user_id: 'veoulla',
      display_name: 'Veoulla',
      role: 'owner',
      gate_code_plaintext: '1234',
      admin_password_plaintext: 'fixture-admin-pass',
      active: 'TRUE',
      default_language: 'en',
      notes: 'fixture',
    }),
  ],
  '03_SECRETS_DEV': [
    headerFor('03_SECRETS_DEV'),
    row('03_SECRETS_DEV', {
      secret_id: 'secret_gemini_fixture',
      service_name: 'gemini',
      key_name: 'api_key',
      plaintext_value: 'FAKE_GEMINI_KEY_NOT_REAL',
      environment: 'dev',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
    row('03_SECRETS_DEV', {
      secret_id: 'secret_weather_fixture',
      service_name: 'weather',
      key_name: 'api_key',
      plaintext_value: 'FAKE_WEATHER_KEY_NOT_REAL',
      environment: 'dev',
      enabled: 'FALSE',
      notes: 'disabled fixture',
    }),
  ],
  '04_ADMIN_FLAGS': [
    headerFor('04_ADMIN_FLAGS'),
    row('04_ADMIN_FLAGS', {
      flag_id: 'force_first_journey',
      scope: 'global',
      value: '0',
      value_type: 'boolean',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '05_ENTRY_LOGS': [
    headerFor('05_ENTRY_LOGS'),
    row('05_ENTRY_LOGS', {
      log_id: 'log_fixture_1',
      timestamp: '2026-01-01T00:00:00.000Z',
      user_id: 'veoulla',
      session_id: 'sess_fixture_1',
      event_type: 'page_open',
      access_result: 'pending',
      ip_address: '203.0.113.10',
      user_agent: 'fixture-agent',
      device_id: 'device_fixture_1',
      language: 'en',
      route: '/',
      details_json: '{}',
    }),
  ],
  '06_SESSIONS': [
    headerFor('06_SESSIONS'),
    row('06_SESSIONS', {
      session_id: 'sess_fixture_1',
      user_id: 'veoulla',
      created_at: '2026-01-01T00:00:00.000Z',
      last_seen_at: '2026-01-01T00:05:00.000Z',
      expires_at: '2026-01-02T00:00:00.000Z',
      ip_address: '203.0.113.10',
      device_id: 'device_fixture_1',
      status: 'active',
      gate_code_id: 'gate_v1',
      current_location: 'gate',
      current_story_beat: 'beat_01',
    }),
  ],
  '07_LANGUAGES': [
    headerFor('07_LANGUAGES'),
    row('07_LANGUAGES', {
      locale_id: 'en',
      short_code: 'EN',
      english_name: 'English',
      native_name: 'English',
      direction: 'ltr',
      enabled: 'TRUE',
      sort_order: '1',
      voice_locale: 'en-US',
      number_locale: 'en-US',
    }),
    row('07_LANGUAGES', {
      locale_id: 'ar-EG',
      short_code: 'AR',
      english_name: 'Egyptian Arabic',
      native_name: 'العربية المصرية',
      direction: 'rtl',
      fallback_locale: 'en',
      enabled: 'TRUE',
      sort_order: '2',
      voice_locale: 'ar-EG',
      number_locale: 'ar-EG',
    }),
    row('07_LANGUAGES', {
      locale_id: 'it',
      short_code: 'IT',
      english_name: 'Italian',
      native_name: 'Italiano',
      direction: 'ltr',
      fallback_locale: 'en',
      enabled: 'TRUE',
      sort_order: '3',
      voice_locale: 'it-IT',
      number_locale: 'it-IT',
    }),
    row('07_LANGUAGES', {
      locale_id: 'el',
      short_code: 'EL',
      english_name: 'Greek',
      native_name: 'Ελληνικά',
      direction: 'ltr',
      fallback_locale: 'en',
      enabled: 'TRUE',
      sort_order: '4',
      voice_locale: 'el-GR',
      number_locale: 'el-GR',
    }),
    row('07_LANGUAGES', {
      locale_id: 'fr',
      short_code: 'FR',
      english_name: 'French',
      native_name: 'Français',
      direction: 'ltr',
      fallback_locale: 'en',
      enabled: 'TRUE',
      sort_order: '5',
      voice_locale: 'fr-FR',
      number_locale: 'fr-FR',
    }),
  ],
  '08_UI_TEXT': [
    headerFor('08_UI_TEXT'),
    row('08_UI_TEXT', {
      ui_text_row_id: 'uit_home_title_en',
      text_id: 'home_title',
      screen_id: 'home',
      component_id: 'title',
      locale: 'en',
      text: "Veoulla's World",
      direction: 'ltr',
      aria_label: 'Home title',
      enabled: 'TRUE',
      version: '1',
    }),
    row('08_UI_TEXT', {
      ui_text_row_id: 'uit_home_title_ar',
      text_id: 'home_title',
      screen_id: 'home',
      component_id: 'title',
      locale: 'ar-EG',
      text: 'عالم فيولا',
      direction: 'rtl',
      aria_label: 'عنوان الصفحة',
      enabled: 'TRUE',
      version: '1',
    }),
    ...(
      [
        ['en', 'Happy Birthday, Veoulla!', 'ltr'],
        ['ar-EG', 'عيد ميلاد سعيد يا فيولا!', 'rtl'],
        ['it', 'Buon compleanno, Veoulla!', 'ltr'],
        ['el', 'Χρόνια πολλά, Βεούλα!', 'ltr'],
        ['fr', 'Joyeux anniversaire, Veoulla !', 'ltr'],
      ] as const
    ).map(([locale, text, direction]) =>
      row('08_UI_TEXT', {
        ui_text_row_id: `uit_ach_birthday_2026_title_${locale}`,
        text_id: 'ach_birthday_2026_title',
        screen_id: 'achievements',
        component_id: 'title',
        locale,
        text,
        direction,
        aria_label: text,
        enabled: 'TRUE',
        version: '1',
      }),
    ),
    ...(
      [
        ['en', 'Celebrated together in the Cottage garden.', 'ltr'],
        ['ar-EG', 'احتفلتي مع الكل في جنينة الكوتيدج.', 'rtl'],
        ['it', 'Festeggiato insieme nel giardino del Cottage.', 'ltr'],
        ['el', 'Γιορτάσαμε μαζί στον κήπο του Cottage.', 'ltr'],
        ['fr', 'Fêté ensemble dans le jardin du Cottage.', 'ltr'],
      ] as const
    ).map(([locale, text, direction]) =>
      row('08_UI_TEXT', {
        ui_text_row_id: `uit_ach_birthday_2026_desc_${locale}`,
        text_id: 'ach_birthday_2026_desc',
        screen_id: 'achievements',
        component_id: 'description',
        locale,
        text,
        direction,
        aria_label: text,
        enabled: 'TRUE',
        version: '1',
      }),
    ),
  ],
  '09_ICONS': [
    headerFor('09_ICONS'),
    row('09_ICONS', {
      icon_id: 'icon_map',
      category: 'ui',
      display_name: 'Map',
      asset_id: 'asset_icon_map',
      format: 'svg',
      rtl_mirror: 'FALSE',
      alt_text_id: 'ui_map',
      width_px: '48',
      height_px: '48',
      enabled: 'TRUE',
      version: '1',
    }),
    row('09_ICONS', {
      icon_id: 'icon_language',
      category: 'ui',
      display_name: 'Language',
      asset_id: 'asset_icon_language',
      format: 'svg',
      rtl_mirror: 'FALSE',
      alt_text_id: 'ui_language',
      width_px: '48',
      height_px: '48',
      enabled: 'TRUE',
      version: '1',
    }),
    row('09_ICONS', {
      icon_id: 'icon_key_shell',
      category: 'key',
      display_name: 'Shell Key',
      asset_id: 'asset_icon_key_shell',
      format: 'svg',
      rtl_mirror: 'FALSE',
      alt_text_id: 'key_shell',
      width_px: '32',
      height_px: '32',
      enabled: 'TRUE',
      version: '1',
    }),
  ],
  '10_ASSETS': [
    headerFor('10_ASSETS'),
    row('10_ASSETS', {
      asset_id: 'asset_icon_map',
      asset_type: 'image',
      drive_file_id: 'fake_drive_id_icon_map',
      preload_priority: '1',
      loop: 'FALSE',
      enabled: 'TRUE',
      version: '1',
      notes: 'fixture',
    }),
    row('10_ASSETS', {
      asset_id: 'asset_icon_language',
      asset_type: 'image',
      drive_file_id: 'fake_drive_id_icon_language',
      preload_priority: '1',
      loop: 'FALSE',
      enabled: 'TRUE',
      version: '1',
      notes: 'fixture',
    }),
    row('10_ASSETS', {
      asset_id: 'asset_icon_key_shell',
      asset_type: 'image',
      location_id: 'beach',
      drive_file_id: 'fake_drive_id_icon_key_shell',
      preload_priority: '1',
      loop: 'FALSE',
      enabled: 'TRUE',
      version: '1',
      notes: 'fixture',
    }),
    row('10_ASSETS', {
      asset_id: 'asset_gate_bg',
      asset_type: 'image',
      location_id: 'gate',
      scene_id: 'scene_gate_closed',
      drive_file_id: '<DRIVE_FILE_ID_GATE_DESKTOP>',
      mobile_drive_file_id: '<DRIVE_FILE_ID_GATE_MOBILE>',
      preload_priority: '1',
      loop: 'FALSE',
      enabled: 'TRUE',
      version: '1',
      notes:
        'Intentional placeholder — mirrors the real blueprint pending final art (expected WARNING).',
    }),
  ],
  '11_LOCATIONS': [
    headerFor('11_LOCATIONS'),
    row('11_LOCATIONS', {
      location_id: 'gate',
      display_name_text_id: 'location_gate',
      map_order: '0',
      road_side: 'outside',
      elevation_band: 'gateway',
      first_visit_order: '1',
      entry_scene_id: 'scene_gate_closed',
      ambient_asset_id: 'audio_gate_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'beach',
      display_name_text_id: 'location_beach',
      subtitle_text_id: 'subtitle_beach',
      map_order: '1',
      road_side: 'center',
      elevation_band: 'beach',
      first_visit_order: '2',
      entry_scene_id: 'scene_beach_arrival',
      key_type_id: 'key_shell',
      ambient_asset_id: 'audio_beach_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'church',
      display_name_text_id: 'location_church',
      map_order: '2',
      road_side: 'left',
      elevation_band: 'road',
      first_visit_order: '3',
      entry_scene_id: 'scene_church_approach',
      key_type_id: 'key_candle',
      ambient_asset_id: 'audio_church_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'cafe',
      display_name_text_id: 'location_cafe',
      map_order: '3',
      road_side: 'right',
      elevation_band: 'road',
      first_visit_order: '4',
      entry_scene_id: 'scene_cafe_approach',
      key_type_id: 'key_music',
      ambient_asset_id: 'audio_cafe_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'arcade',
      display_name_text_id: 'location_arcade',
      map_order: '4',
      road_side: 'right',
      elevation_band: 'road',
      first_visit_order: '5',
      entry_scene_id: 'scene_arcade_approach',
      key_type_id: 'key_token',
      ambient_asset_id: 'audio_arcade_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'cottage',
      display_name_text_id: 'location_cottage',
      map_order: '5',
      road_side: 'right',
      elevation_band: 'upper_road',
      first_visit_order: '6',
      entry_scene_id: 'scene_cottage_approach',
      key_type_id: 'key_letter',
      ambient_asset_id: 'audio_cottage_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'farm',
      display_name_text_id: 'location_farm',
      subtitle_text_id: 'subtitle_farm',
      map_order: '6',
      road_side: 'left',
      elevation_band: 'road',
      first_visit_order: '7',
      entry_scene_id: 'scene_farm_approach',
      key_type_id: 'key_sunflower',
      ambient_asset_id: 'audio_farm_ambient',
      enabled: 'TRUE',
    }),
    row('11_LOCATIONS', {
      location_id: 'museum',
      display_name_text_id: 'location_museum',
      subtitle_text_id: 'subtitle_museum',
      map_order: '7',
      road_side: 'center',
      elevation_band: 'museum',
      first_visit_order: '8',
      entry_scene_id: 'scene_museum_approach',
      key_type_id: 'key_everkeep',
      ambient_asset_id: 'audio_museum_ambient',
      enabled: 'TRUE',
    }),
  ],
  '12_SCENES': [
    headerFor('12_SCENES'),
    ...(['gate', 'beach', 'church', 'cafe', 'arcade', 'cottage', 'farm', 'museum'] as const).map(
      (location) =>
        row('12_SCENES', {
          scene_id: LOCATION_SCENE[location]!,
          location_id: location,
          scene_type: 'exterior',
          display_name: `${location} scene`,
          entry_transition: 'fade',
          exit_transition: 'fade',
          camera_mode: 'first_person',
          movement_profile: 'rail',
          ambient_audio_id: `audio_${location}_ambient`,
          enabled: 'TRUE',
        }),
    ),
  ],
  '13_ROUTES': [
    headerFor('13_ROUTES'),
    row('13_ROUTES', {
      route_id: 'first_journey',
      route_name: 'First Journey',
      route_type: 'story',
      start_scene_id: 'scene_gate_closed',
      end_scene_id: 'scene_museum_approach',
      mandatory_once: 'TRUE',
      allow_skip_after_complete: 'TRUE',
      active_version: 'first_journey_v1',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '14_STORY_BEATS': [headerFor('14_STORY_BEATS'), ...buildStoryBeats()],
  '15_DIALOGUE': [
    headerFor('15_DIALOGUE'),
    row('15_DIALOGUE', {
      dialogue_row_id: 'dlg_boot_en',
      dialogue_id: 'dlg_boot',
      group_id: 'grp_boot',
      sequence: '1',
      speaker_id: 'char_var',
      locale: 'en',
      text: 'Hello',
      direction: 'ltr',
      emotion: 'warm',
      display_mode: 'speech_bubble',
      voiceover_id: 'vo_boot_en',
      requires_response: 'FALSE',
      enabled: 'TRUE',
    }),
  ],
  '16_VOICEOVER': [
    headerFor('16_VOICEOVER'),
    row('16_VOICEOVER', {
      voiceover_id: 'vo_boot_en',
      content_type: 'dialogue',
      content_id: 'dlg_boot',
      locale: 'en',
      audio_asset_id: 'asset_vo_boot_en',
      caption_text: 'Hello',
      direction: 'ltr',
      voice_name: 'var_voice',
      duration_ms: '2000',
      caption_start_ms: '0',
      caption_end_ms: '2000',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '17_EVENTS': [
    headerFor('17_EVENTS'),
    row('17_EVENTS', {
      event_id: 'birthday_2026',
      event_name: 'Fixture Birthday',
      event_type: 'birthday',
      // 2026-09-26 00:00 / 2026-09-28 00:00 Africa/Cairo (UTC+3, daylight saving time) — the approved M16 window.
      target_at: '2026-09-25T21:00:00.000Z',
      time_zone: 'Africa/Cairo',
      start_at: '2026-09-25T21:00:00.000Z',
      end_at: '2026-09-27T21:00:00.000Z',
      enabled: 'TRUE',
      story_route_id: '',
      force_flag_id: 'force_birthday_story',
      replay_allowed: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '18_EVENT_PHASES': [
    headerFor('18_EVENT_PHASES'),
    row('18_EVENT_PHASES', {
      phase_id: 'phase_b0',
      event_id: 'birthday_2026',
      sequence: '1',
      start_offset_minutes: '-1440',
      end_offset_minutes: '-360',
      phase_name: 'Ordinary world',
      visual_theme_id: 'theme_default',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '19_MESSAGES': [
    headerFor('19_MESSAGES'),
    row('19_MESSAGES', {
      message_row_id: 'msg_first_en',
      message_id: 'msg_first',
      sender_id: 'ahmed',
      recipient_user_id: 'veoulla',
      delivery_at: '2026-01-01T00:00:00.000Z',
      priority: 'high',
      message_type: 'text',
      locale: 'en',
      text: 'Welcome!',
      direction: 'ltr',
      translation_group_id: 'grp_msg_first',
      archive_after_open: 'FALSE',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
    // Ahmed's birthday letter (draft). `ar-EG` is his own authored text; the other four locales are
    // draft translations pending his review — see docs/reports for the M16 evidence report. Delivery
    // itself is governed by `world/birthday.ts`'s `claimGifts` (never `deliverDueMessages`), so
    // `delivery_at` here is documentation only, not a gate.
    ...(
      [
        [
          'en',
          'msg_birthday_2026_en',
          'ltr',
          'Veoulla 🤍\nHappy birthday, dear Professor Doctor Engineer, the lovely Miss Veoulla!\nI hope your new year brings rest for your heart, laughter without counting,\nand steps that bring you closer to the things you wish for.\nI’m happy for our friendship, and I wanted you to have a celebration here\nyou can come back to whenever you like. Take your time, make a wish, and celebrate your way.\nEvery year, you have a dear place with me 💜\n— Ahmed',
        ],
        [
          'ar-EG',
          'msg_birthday_2026_ar',
          'rtl',
          'يا فيولا 🤍\nكل سنة وإنتِ طيبة يا بروفسيرة دكتورة بشمهندسة الآنسة الجميلة فيولا!\nأتمنى سنتك الجديدة يكون فيها راحة لقلبك، وضحك من غير حساب،\nوخطوات تقرّبك من الحاجات اللي نفسك فيها.\nأنا مبسوط بصداقتنا، وحبيت يكون ليكي هنا احتفال تقدري ترجعي له\nكل ما تحبي. خدي وقتك، اتمني أمنية، واحتفلي بطريقتك.\nكل سنة وإنتِ ليكي مكان غالي عندي 💜\n— أحمد',
        ],
        [
          'it',
          'msg_birthday_2026_it',
          'ltr',
          'Veoulla 🤍\nBuon compleanno, cara Professoressa Dottoressa Ingegnera, la bella signorina Veoulla!\nSpero che il tuo nuovo anno porti riposo al tuo cuore, risate senza contarle,\ne passi che ti avvicinino alle cose che desideri.\nSono felice della nostra amicizia, e ho voluto che tu avessi qui una festa a cui tornare\nogni volta che vuoi. Prenditi il tuo tempo, esprimi un desiderio, e festeggia a modo tuo.\nOgni anno, hai un posto caro nel mio cuore 💜\n— Ahmed',
        ],
        [
          'el',
          'msg_birthday_2026_el',
          'ltr',
          'Βεούλα 🤍\nΧρόνια πολλά, αγαπητή Καθηγήτρια Δόκτωρ Μηχανικέ, όμορφη δεσποινίς Βεούλα!\nΕύχομαι ο νέος σου χρόνος να φέρει ανάπαυση στην καρδιά σου, γέλιο χωρίς μέτρημα,\nκαι βήματα που θα σε φέρουν πιο κοντά σε ό,τι επιθυμείς.\nΧαίρομαι για τη φιλία μας, και ήθελα να έχεις εδώ μια γιορτή που μπορείς να επισκέπτεσαι\nόποτε θέλεις. Πάρε τον χρόνο σου, κάνε μια ευχή, και γιόρτασε με τον δικό σου τρόπο.\nΚάθε χρόνο, έχεις μια αγαπημένη θέση δίπλα μου 💜\n— Ahmed',
        ],
        [
          'fr',
          'msg_birthday_2026_fr',
          'ltr',
          'Veoulla 🤍\nJoyeux anniversaire, chère Professeure Docteure Ingénieure, la charmante Mademoiselle Veoulla !\nJ’espère que ta nouvelle année apportera du repos à ton cœur, des rires sans compter,\net des pas qui te rapprochent de ce que tu souhaites.\nJe suis heureux de notre amitié, et j’ai voulu que tu aies ici une célébration à laquelle revenir\nquand tu veux. Prends ton temps, fais un vœu, et célèbre à ta façon.\nChaque année, tu as une place précieuse auprès de moi 💜\n— Ahmed',
        ],
      ] as const
    ).map(([locale, rowId, direction, text]) =>
      row('19_MESSAGES', {
        message_row_id: rowId,
        message_id: 'msg_birthday_2026',
        sender_id: 'ahmed',
        recipient_user_id: 'veoulla',
        delivery_at: '2026-09-25T21:00:00.000Z',
        priority: 'high',
        message_type: 'letter',
        locale,
        text,
        direction,
        image_asset_ids: '',
        gift_ids: 'birthday_2026_celebrated,birthday_cottage_decoration',
        translation_group_id: 'grp_msg_birthday_2026',
        archive_after_open: 'FALSE',
        // Enabled in this TEST fixture so the flow is fully testable. The real Sheet row this
        // seeds from (scripts/seed-birthday-event.mjs, not yet run) stays `enabled: FALSE` — a
        // deliberate draft — until Ahmed approves the wording.
        enabled: 'TRUE',
        notes:
          'fixture — draft letter, EN/IT/EL/FR are unapproved translations of Ahmed’s ar-EG text',
      }),
    ),
  ],
  '20_SONGS': [
    headerFor('20_SONGS'),
    row('20_SONGS', {
      song_id: 'song_fixture_1',
      title: 'Fixture Song',
      artist: 'Fixture Artist',
      release_at: '2026-01-01T00:00:00.000Z',
      location_id: 'cafe',
      audio_asset_id: 'asset_song_1',
      cover_asset_id: 'asset_song_cover_1',
      explanation_text_id: 'song_1_explain',
      available_in_walkman: 'TRUE',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '21_KEYS': [
    headerFor('21_KEYS'),
    ...[
      ['key_shell', 'beach', 'shell'],
      ['key_candle', 'church', 'candle'],
      ['key_music', 'cafe', 'note'],
      ['key_token', 'arcade', 'coin'],
      ['key_letter', 'cottage', 'envelope'],
      ['key_sunflower', 'farm', 'sunflower'],
      ['key_everkeep', 'museum', 'ancient_key'],
    ].map(([keyTypeId, locationId, shape]) =>
      row('21_KEYS', {
        key_type_id: keyTypeId!,
        location_id: locationId!,
        display_name_text_id: `${keyTypeId}_name`,
        shape: shape!,
        icon_id: 'icon_key_shell',
        max_per_day: '1',
        rarity: keyTypeId === 'key_everkeep' ? 'legendary' : 'common',
        inventory_cap: keyTypeId === 'key_everkeep' ? '9' : '99',
        enabled: 'TRUE',
        notes: 'fixture',
      }),
    ),
  ],
  '22_KEY_RULES': [
    headerFor('22_KEY_RULES'),
    row('22_KEY_RULES', {
      rule_id: 'rule_key_shell_1',
      key_type_id: 'key_shell',
      source_type: 'beat',
      source_id: 'beat_02',
      required_story_beat: 'beat_02',
      max_awards_per_period: '1',
      period_type: 'day',
      reward_quantity: '1',
      condition_json: '{}',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '23_ACHIEVEMENTS': [
    headerFor('23_ACHIEVEMENTS'),
    row('23_ACHIEVEMENTS', {
      achievement_id: 'ach_first_key',
      category: 'keys',
      title_text_id: 'ach_first_key_title',
      description_text_id: 'ach_first_key_desc',
      icon_id: 'icon_key_shell',
      secret: 'FALSE',
      points: '10',
      trigger_type: 'key_award',
      trigger_rule_json: '{}',
      reward_key_type_id: 'key_shell',
      reward_quantity: '0',
      enabled: 'TRUE',
    }),
    row('23_ACHIEVEMENTS', {
      achievement_id: 'birthday_2026_celebrated',
      category: 'birthday',
      title_text_id: 'ach_birthday_2026_title',
      description_text_id: 'ach_birthday_2026_desc',
      icon_id: '',
      secret: 'TRUE',
      points: '10',
      trigger_type: 'birthday_gift_claim',
      trigger_rule_json: '{}',
      // No progression key: birthday_2026's gifts are the letter, the Cottage decoration and this
      // achievement only. Leaving these two blank is what makes `unlockAchievement` skip a key award.
      reward_key_type_id: '',
      reward_quantity: '0',
      enabled: 'TRUE',
    }),
  ],
  '24_PLAYER_PROGRESS': [
    headerFor('24_PLAYER_PROGRESS'),
    row('24_PLAYER_PROGRESS', {
      user_route_key: 'veoulla|first_journey',
      user_id: 'veoulla',
      story_route_id: 'first_journey',
      story_version: 'first_journey_v1',
      status: 'not_started',
      current_beat_id: 'beat_01',
      first_journey_completed: '0',
      force_first_journey: '0',
      map_unlocked: 'FALSE',
      current_location: 'gate',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '25_PLAYER_KEYS': [
    headerFor('25_PLAYER_KEYS'),
    row('25_PLAYER_KEYS', {
      user_key_type: 'veoulla|key_shell',
      user_id: 'veoulla',
      key_type_id: 'key_shell',
      quantity_found: '0',
      quantity_spent: '0',
      quantity_available: '0',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '26_PLAYER_ACHIEV': [
    headerFor('26_PLAYER_ACHIEV'),
    row('26_PLAYER_ACHIEV', {
      user_achievement_key: 'veoulla|ach_first_key',
      user_id: 'veoulla',
      achievement_id: 'ach_first_key',
      status: 'not_started',
      progress_value: '0',
      claimed: 'FALSE',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '27_PLAYER_MESSAGES': [
    headerFor('27_PLAYER_MESSAGES'),
    row('27_PLAYER_MESSAGES', {
      user_message_key: 'veoulla|msg_first',
      user_id: 'veoulla',
      message_id: 'msg_first',
      delivery_status: 'delivered',
      read_status: 'unread',
      delivered_at: '2026-01-01T00:00:00.000Z',
      initial_locale: 'en',
      current_translation_locale: 'en',
      voice_played: 'FALSE',
      gift_claimed: 'FALSE',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '28_FARM_CROPS': [
    headerFor('28_FARM_CROPS'),
    row('28_FARM_CROPS', {
      crop_id: 'crop_sunflower',
      display_name_text_id: 'crop_sunflower_name',
      seed_icon_id: 'icon_key_shell',
      crop_icon_id: 'icon_key_shell',
      grow_hours: '24',
      watering_interval_hours: '12',
      wilt_after_hours: '48',
      rain_waters: 'TRUE',
      harvest_yield: '1',
      rarity: 'common',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '29_PLAYER_FARM': [
    headerFor('29_PLAYER_FARM'),
    row('29_PLAYER_FARM', {
      user_plot_key: 'veoulla|plot_1',
      user_id: 'veoulla',
      plot_id: 'plot_1',
      crop_id: 'crop_sunflower',
      state: 'empty',
      harvest_count: '0',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '30_CHURCH_CONTENT': [
    headerFor('30_CHURCH_CONTENT'),
    row('30_CHURCH_CONTENT', {
      content_row_id: 'church_verse_1_en',
      content_id: 'church_verse_1',
      content_type: 'verse',
      active_date: '2026-01-01',
      locale: 'en',
      title: 'Verse title',
      text: 'Verse text',
      direction: 'ltr',
      bible_reference: 'John 3:16',
      review_status: 'approved',
      enabled: 'TRUE',
    }),
  ],
  '31_CHURCH_QUIZ': [
    headerFor('31_CHURCH_QUIZ'),
    row('31_CHURCH_QUIZ', {
      question_row_id: 'quiz_1_en',
      question_id: 'quiz_1',
      active_date: '2026-01-01',
      locale: 'en',
      question: 'Sample question?',
      question_type: 'multiple_choice',
      option_a: 'A',
      option_b: 'B',
      option_c: 'C',
      option_d: 'D',
      correct_answer: 'A',
      explanation: 'Because',
      bible_reference: 'John 3:16',
      key_reward_type_id: 'key_candle',
      enabled: 'TRUE',
      review_status: 'approved',
    }),
  ],
  '32_ARCADE_GAMES': [
    headerFor('32_ARCADE_GAMES'),
    row('32_ARCADE_GAMES', {
      game_id: 'game_memory_1',
      cabinet_slot: '1',
      display_name_text_id: 'game_memory_1_name',
      game_family: 'memory',
      key_cost_quantity: '0',
      difficulty_mode: 'adaptive',
      score_mode: 'high_score',
      walkman_volume_percent: '40',
      music_enabled: 'FALSE',
      sfx_enabled: 'TRUE',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '33_PLAYER_SCORES': [
    headerFor('33_PLAYER_SCORES'),
    row('33_PLAYER_SCORES', {
      attempt_id: 'attempt_1',
      user_id: 'veoulla',
      game_id: 'game_memory_1',
      played_at: '2026-01-01T00:00:00.000Z',
      score: '100',
      difficulty: '1',
      result: 'win',
      personal_best: 'TRUE',
      key_rewarded: 'FALSE',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '34_MUSEUM_EXHIBITS': [
    headerFor('34_MUSEUM_EXHIBITS'),
    row('34_MUSEUM_EXHIBITS', {
      exhibit_id: 'exhibit_central_artifact',
      wing_id: 'central_hall',
      display_name_text_id: 'exhibit_central_artifact_name',
      exhibit_type: 'artifact',
      unlock_type: 'always',
      unlock_rule_json: '{}',
      position_id: 'pos_1',
      personal_only: 'FALSE',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '35_PLAYER_EXHIBITS': [
    headerFor('35_PLAYER_EXHIBITS'),
    row('35_PLAYER_EXHIBITS', {
      user_exhibit_key: 'veoulla|exhibit_central_artifact',
      user_id: 'veoulla',
      exhibit_id: 'exhibit_central_artifact',
      unlock_status: 'locked',
      view_count: '0',
      book_page: '0',
      completed: 'FALSE',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '36_CHARACTERS': [
    headerFor('36_CHARACTERS'),
    row('36_CHARACTERS', {
      character_id: 'char_var',
      system_name: 'VAR',
      display_name_mode: 'player_named',
      default_display_name: 'VAR',
      species: 'cat',
      base_color: 'white',
      eye_color: 'blue',
      gender_mode: 'player_choice',
      home_location_id: 'cottage',
      ai_enabled: 'TRUE',
      dialogue_mode: 'hybrid',
      voice_enabled: 'TRUE',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
    row('36_CHARACTERS', {
      character_id: 'char_marcelino',
      system_name: 'MARCELINO',
      display_name_mode: 'fixed',
      default_display_name: 'Marcelino',
      species: 'chick',
      base_color: 'yellow',
      eye_color: 'black',
      gender_mode: 'fixed',
      home_location_id: 'cottage',
      ai_enabled: 'FALSE',
      dialogue_mode: 'authored',
      voice_enabled: 'FALSE',
      enabled: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '37_CHARACTER_STATE': [
    headerFor('37_CHARACTER_STATE'),
    row('37_CHARACTER_STATE', {
      user_character_key: 'veoulla|char_var',
      user_id: 'veoulla',
      character_id: 'char_var',
      selected_gender: 'unset',
      relationship_level: '0',
      current_location: 'gate',
      current_activity: 'idle',
      last_seen_at: '2026-01-01T00:00:00.000Z',
      mood: 'neutral',
      known_words_count: '0',
      deliveries_count: '0',
      story_flags_json: '{}',
      updated_at: '2026-01-01T00:00:00.000Z',
    }),
  ],
  '38_DATA_DICTIONARY': [headerFor('38_DATA_DICTIONARY'), ...buildDataDictionary()],
  '39_VALIDATION_LISTS': [VALIDATION_LISTS_HEADER, ...VALIDATION_LISTS_ROWS],
  '40_VAR_CONVERSATIONS': [
    headerFor('40_VAR_CONVERSATIONS'),
    row('40_VAR_CONVERSATIONS', {
      turn_id: 'turn_1',
      conversation_id: 'conv_1',
      user_id: 'veoulla',
      session_id: 'sess_fixture_1',
      character_id: 'char_var',
      sequence: '1',
      speaker: 'user',
      locale: 'en',
      message_text: 'Hello',
      gemini_interaction_id: 'fake_interaction_id',
      created_at: '2026-01-01T00:00:00.000Z',
      model_id: 'fake-model',
      input_tokens: '5',
      output_tokens: '0',
      status: 'complete',
      visible_to_player: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '41_VAR_MEMORIES': [
    headerFor('41_VAR_MEMORIES'),
    row('41_VAR_MEMORIES', {
      memory_id: 'mem_1',
      user_id: 'veoulla',
      character_id: 'char_var',
      category: 'preference',
      summary: 'Likes sunflowers',
      source_conversation_id: 'conv_1',
      importance: '3',
      first_seen_at: '2026-01-01T00:00:00.000Z',
      last_confirmed_at: '2026-01-01T00:00:00.000Z',
      active: 'TRUE',
      admin_approved: 'TRUE',
      notes: 'fixture',
    }),
  ],
  '42_ARCADE_TRIVIA': [
    headerFor('42_ARCADE_TRIVIA'),
    row('42_ARCADE_TRIVIA', {
      question_row_id: 'triv_1_en',
      question_id: 'triv_1',
      locale: 'en',
      question: 'Which shape is the Farm key?',
      question_type: 'multiple_choice',
      option_a: 'Sunflower',
      option_b: 'Candle',
      option_c: 'Shell',
      option_d: 'Envelope',
      correct_answer: 'a',
      explanation: 'The Farm key is sunflower-shaped.',
      enabled: 'TRUE',
      review_status: 'pending_review',
    }),
  ],
  '43_COMPANION_HINTS': [
    headerFor('43_COMPANION_HINTS'),
    row('43_COMPANION_HINTS', {
      hint_row_id: 'hint_farm_plant_en',
      hint_id: 'hint_farm_plant',
      location_id: 'farm',
      condition_type: 'story_beat_pending',
      condition_value: 'beat_14_farm',
      priority: '1',
      locale: 'en',
      text: 'Try planting a seed here.',
      direction: 'ltr',
      enabled: 'TRUE',
    }),
  ],
};
