import type { TableTabDefinition } from '../types.js';
import { c } from './column-helper.js';

export const CONTENT_SYSTEM_TABS: TableTabDefinition[] = [
  {
    name: '19_MESSAGES',
    kind: 'table',
    purpose: 'Scheduled multilingual messages, gifts, images, and voice notes.',
    primaryKey: 'message_row_id',
    columns: [
      c('message_row_id', 'id'),
      c('message_id', 'text'),
      c('sender_id', 'id'),
      c('recipient_user_id', 'id'),
      c('delivery_at', 'date'),
      c('priority', 'text'),
      c('message_type', 'text'),
      c('locale', 'text', { controlledList: 'locale' }),
      c('text', 'text'),
      c('direction', 'text', { controlledList: 'direction' }),
      c('image_asset_ids', 'csv'),
      c('voiceover_id', 'id'),
      c('gift_ids', 'csv'),
      c('translation_group_id', 'text'),
      c('archive_after_open', 'boolean'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
    notes: 'message_id repeats across locale rows; message_row_id is the real primary key.',
  },
  {
    name: '20_SONGS',
    kind: 'table',
    purpose: 'Vinyl Café and Walkman catalog referencing Drive-backed audio assets.',
    primaryKey: 'song_id',
    columns: [
      c('song_id', 'id'),
      c('title', 'text'),
      c('artist', 'text'),
      c('release_at', 'date'),
      c('location_id', 'text', { controlledList: 'location' }),
      c('audio_asset_id', 'id'),
      c('cover_asset_id', 'id'),
      c('explanation_text_id', 'text'),
      c('available_in_walkman', 'boolean'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '21_KEYS',
    kind: 'table',
    purpose: 'Canonical key types, shapes, daily caps, and locations.',
    primaryKey: 'key_type_id',
    columns: [
      c('key_type_id', 'id'),
      c('location_id', 'text', { controlledList: 'location' }),
      c('display_name_text_id', 'text'),
      c('shape', 'text'),
      c('icon_id', 'id'),
      c('max_per_day', 'integer'),
      c('rarity', 'text'),
      c('inventory_cap', 'integer'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '22_KEY_RULES',
    kind: 'table',
    purpose: 'Date, story, interaction, and reward rules for every key award.',
    primaryKey: 'rule_id',
    columns: [
      c('rule_id', 'id'),
      c('key_type_id', 'id'),
      c('source_type', 'text'),
      c('source_id', 'text'),
      c('available_from', 'date'),
      c('available_to', 'date'),
      c('required_story_beat', 'id'),
      c('max_awards_per_period', 'integer'),
      c('period_type', 'text'),
      c('reward_quantity', 'integer'),
      c('condition_json', 'json'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '23_ACHIEVEMENTS',
    kind: 'table',
    purpose: 'Visible/secret achievements, triggers, and rewards.',
    primaryKey: 'achievement_id',
    columns: [
      c('achievement_id', 'id'),
      c('category', 'text'),
      c('title_text_id', 'text'),
      c('description_text_id', 'text'),
      c('icon_id', 'id'),
      c('secret', 'boolean'),
      c('points', 'integer'),
      c('trigger_type', 'text'),
      c('trigger_rule_json', 'json'),
      c('reward_key_type_id', 'id'),
      c('reward_quantity', 'integer'),
      c('enabled', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '28_FARM_CROPS',
    kind: 'table',
    purpose: 'Sheet-driven crop durations, watering, wilt, rain, yield, and rarity.',
    primaryKey: 'crop_id',
    columns: [
      c('crop_id', 'id'),
      c('display_name_text_id', 'text'),
      c('seed_icon_id', 'id'),
      c('crop_icon_id', 'id'),
      c('grow_hours', 'integer'),
      c('watering_interval_hours', 'integer'),
      c('wilt_after_hours', 'integer'),
      c('rain_waters', 'boolean'),
      c('harvest_yield', 'integer'),
      c('rarity', 'text'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '30_CHURCH_CONTENT',
    kind: 'table',
    purpose: 'Reviewed dated verses, stories, images, narration, and sources.',
    primaryKey: 'content_row_id',
    columns: [
      c('content_row_id', 'id'),
      c('content_id', 'text'),
      c('content_type', 'text'),
      c('active_date', 'date'),
      c('locale', 'text', { controlledList: 'locale' }),
      c('title', 'text'),
      c('text', 'text'),
      c('direction', 'text', { controlledList: 'direction' }),
      c('image_asset_ids', 'csv'),
      c('voiceover_id', 'id'),
      c('bible_reference', 'text'),
      c('source_url', 'text'),
      c('review_status', 'text', { controlledList: 'review_status' }),
      c('enabled', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
    notes: 'content_id repeats across locale rows; content_row_id is the real primary key.',
  },
  {
    name: '31_CHURCH_QUIZ',
    kind: 'table',
    purpose: 'Reviewed multiple-choice and true/false Bible quiz bank.',
    primaryKey: 'question_row_id',
    columns: [
      c('question_row_id', 'id'),
      c('question_id', 'text'),
      c('active_date', 'date'),
      c('locale', 'text', { controlledList: 'locale' }),
      c('question', 'text'),
      c('question_type', 'text'),
      c('option_a', 'text'),
      c('option_b', 'text'),
      c('option_c', 'text'),
      c('option_d', 'text'),
      c('correct_answer', 'text'),
      c('explanation', 'text'),
      c('bible_reference', 'text'),
      c('achievement_id', 'id'),
      c('key_reward_type_id', 'id'),
      c('enabled', 'boolean'),
      c('review_status', 'text', { controlledList: 'review_status' }),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
    notes: 'question_id repeats across locale rows; question_row_id is the real primary key.',
  },
  {
    name: '32_ARCADE_GAMES',
    kind: 'table',
    purpose: 'Cabinets, game family, unlock, adaptive difficulty, scoring, and audio rules.',
    primaryKey: 'game_id',
    columns: [
      c('game_id', 'id'),
      c('cabinet_slot', 'integer'),
      c('display_name_text_id', 'text'),
      c('game_family', 'text'),
      c('unlock_rule_id', 'text'),
      c('key_cost_type_id', 'id'),
      c('key_cost_quantity', 'integer'),
      c('difficulty_mode', 'text'),
      c('score_mode', 'text'),
      c('walkman_volume_percent', 'integer'),
      c('music_enabled', 'boolean'),
      c('sfx_enabled', 'boolean'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '34_MUSEUM_EXHIBITS',
    kind: 'table',
    purpose: 'Everkeep exhibits, wings, sources, unlocks, media, and personal access.',
    primaryKey: 'exhibit_id',
    columns: [
      c('exhibit_id', 'id'),
      c('wing_id', 'text'),
      c('display_name_text_id', 'text'),
      c('exhibit_type', 'text'),
      c('source_content_id', 'text'),
      c('unlock_type', 'text'),
      c('unlock_rule_json', 'json'),
      c('position_id', 'text'),
      c('image_asset_ids', 'csv'),
      c('audio_asset_id', 'id'),
      c('personal_only', 'boolean'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '36_CHARACTERS',
    kind: 'table',
    purpose: 'Canonical VAR and Marcelino identity, behavior, dialogue, and home settings.',
    primaryKey: 'character_id',
    columns: [
      c('character_id', 'id'),
      c('system_name', 'text'),
      c('display_name_mode', 'text'),
      c('default_display_name', 'text'),
      c('species', 'text'),
      c('base_color', 'text'),
      c('eye_color', 'text'),
      c('gender_mode', 'text'),
      c('home_location_id', 'text', { controlledList: 'location' }),
      c('ai_enabled', 'boolean'),
      c('dialogue_mode', 'text'),
      c('voice_enabled', 'boolean'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
];
