import type { TableTabDefinition } from '../types.js';
import { c } from './column-helper.js';

export const LOCALIZATION_MEDIA_TABS: TableTabDefinition[] = [
  {
    name: '07_LANGUAGES',
    kind: 'table',
    purpose: 'Locale, direction, fallback, and voice metadata.',
    primaryKey: 'locale_id',
    columns: [
      c('locale_id', 'id', { controlledList: 'locale' }),
      c('short_code', 'text'),
      c('english_name', 'text'),
      c('native_name', 'text'),
      c('direction', 'text', { controlledList: 'direction' }),
      c('fallback_locale', 'text'),
      c('enabled', 'boolean'),
      c('sort_order', 'integer'),
      c('voice_locale', 'text'),
      c('number_locale', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '08_UI_TEXT',
    kind: 'table',
    purpose: 'Normalized UI labels and accessibility text in five languages.',
    primaryKey: 'ui_text_row_id',
    columns: [
      c('ui_text_row_id', 'id'),
      c('text_id', 'text'),
      c('screen_id', 'text'),
      c('component_id', 'text'),
      c('locale', 'text', { controlledList: 'locale' }),
      c('text', 'text'),
      c('direction', 'text', { controlledList: 'direction' }),
      c('aria_label', 'text'),
      c('enabled', 'boolean'),
      c('version', 'integer'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
    notes:
      'text_id is a content group shared across locale rows; ui_text_row_id is the real primary key.',
  },
  {
    name: '09_ICONS',
    kind: 'table',
    purpose: 'All interface, location, key, language, and event icons referencing 10_ASSETS.',
    primaryKey: 'icon_id',
    columns: [
      c('icon_id', 'id'),
      c('category', 'text'),
      c('display_name', 'text'),
      c('asset_id', 'id'),
      c('format', 'text'),
      c('rtl_mirror', 'boolean'),
      c('alt_text_id', 'text'),
      c('width_px', 'integer'),
      c('height_px', 'integer'),
      c('enabled', 'boolean'),
      c('version', 'integer'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '10_ASSETS',
    kind: 'table',
    purpose:
      'Central versioned Google Drive file IDs for every image, video, audio, poster, PDF, SVG, and animation.',
    primaryKey: 'asset_id',
    columns: [
      c('asset_id', 'id'),
      c('asset_type', 'text'),
      c('location_id', 'text', { controlledList: 'location' }),
      c('scene_id', 'id'),
      c('drive_file_id', 'text', { sensitive: true }),
      c('mobile_drive_file_id', 'text', { sensitive: true }),
      c('poster_drive_file_id', 'text', { sensitive: true }),
      c('preload_priority', 'integer'),
      c('loop', 'boolean'),
      c('enabled', 'boolean'),
      c('version', 'integer'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
    notes:
      'Drive file ID columns are marked sensitive: the bootstrap API must resolve these to a future application media URL/ID and never forward the raw Drive file ID to the browser.',
  },
];
