import type { TableTabDefinition } from '../types.js';
import { c } from './column-helper.js';

export const PLAYER_STATE_TABS: TableTabDefinition[] = [
  {
    name: '24_PLAYER_PROGRESS',
    kind: 'table',
    purpose: 'Sheet-authoritative story checkpoints, completion, Map state, and current location.',
    primaryKey: 'user_route_key',
    columns: [
      c('user_route_key', 'id'),
      c('user_id', 'id'),
      c('story_route_id', 'id'),
      c('story_version', 'text'),
      c('status', 'text', { controlledList: 'progress_status' }),
      c('current_beat_id', 'id'),
      c('last_checkpoint_id', 'id'),
      c('started_at', 'date'),
      c('completed_at', 'date'),
      c('first_journey_completed', 'boolean'),
      c('force_first_journey', 'boolean'),
      c('map_unlocked', 'boolean'),
      c('current_location', 'text', { controlledList: 'location' }),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '25_PLAYER_KEYS',
    kind: 'table',
    purpose: 'Sheet-authoritative found, spent, and available key inventory.',
    primaryKey: 'user_key_type',
    columns: [
      c('user_key_type', 'id'),
      c('user_id', 'id'),
      c('key_type_id', 'id'),
      c('quantity_found', 'integer'),
      c('quantity_spent', 'integer'),
      c('quantity_available', 'integer'),
      c('last_found_at', 'date'),
      c('last_source_id', 'text'),
      c('last_award_date', 'date'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '26_PLAYER_ACHIEV',
    kind: 'table',
    purpose: 'Per-user achievement progress, unlock, claim, and reward state.',
    primaryKey: 'user_achievement_key',
    columns: [
      c('user_achievement_key', 'id'),
      c('user_id', 'id'),
      c('achievement_id', 'id'),
      c('status', 'text'),
      c('progress_value', 'integer'),
      c('unlocked_at', 'date'),
      c('claimed', 'boolean'),
      c('reward_claimed_at', 'date'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '27_PLAYER_MESSAGES',
    kind: 'table',
    purpose: 'Delivery, read, archive, translation, voice, and gift status per message.',
    primaryKey: 'user_message_key',
    columns: [
      c('user_message_key', 'id'),
      c('user_id', 'id'),
      c('message_id', 'text'),
      c('delivery_status', 'text'),
      c('read_status', 'text', { controlledList: 'message_read_status' }),
      c('delivered_at', 'date'),
      c('opened_at', 'date'),
      c('archived_at', 'date'),
      c('initial_locale', 'text', { controlledList: 'locale' }),
      c('current_translation_locale', 'text', { controlledList: 'locale' }),
      c('voice_played', 'boolean'),
      c('gift_claimed', 'boolean'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '29_PLAYER_FARM',
    kind: 'table',
    purpose: 'Per-plot planting, watering, ready, wilt, and harvest state.',
    primaryKey: 'user_plot_key',
    columns: [
      c('user_plot_key', 'id'),
      c('user_id', 'id'),
      c('plot_id', 'text'),
      c('crop_id', 'id'),
      c('state', 'text', { controlledList: 'farm_state' }),
      c('planted_at', 'date'),
      c('last_watered_at', 'date'),
      c('next_water_due_at', 'date'),
      c('ready_at', 'date'),
      c('wilted_at', 'date'),
      c('harvest_count', 'integer'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '33_PLAYER_SCORES',
    kind: 'table',
    purpose: 'Arcade attempts, adaptive difficulty, personal bests, and rewards.',
    primaryKey: 'attempt_id',
    columns: [
      c('attempt_id', 'id'),
      c('user_id', 'id'),
      c('game_id', 'id'),
      c('played_at', 'date'),
      c('score', 'integer'),
      c('difficulty', 'text'),
      c('result', 'text'),
      c('personal_best', 'boolean'),
      c('achievement_ids', 'csv'),
      c('key_rewarded', 'boolean'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '35_PLAYER_EXHIBITS',
    kind: 'table',
    purpose: 'Per-user exhibit unlock, view, book progress, and completion.',
    primaryKey: 'user_exhibit_key',
    columns: [
      c('user_exhibit_key', 'id'),
      c('user_id', 'id'),
      c('exhibit_id', 'id'),
      c('unlock_status', 'text'),
      c('unlocked_at', 'date'),
      c('view_count', 'integer'),
      c('last_viewed_at', 'date'),
      c('book_page', 'integer'),
      c('completed', 'boolean'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '37_CHARACTER_STATE',
    kind: 'table',
    purpose: 'Per-user character names, gender, mood, location, learning, and story flags.',
    primaryKey: 'user_character_key',
    columns: [
      c('user_character_key', 'id'),
      c('user_id', 'id'),
      c('character_id', 'id'),
      c('personal_name', 'text'),
      c('selected_gender', 'text'),
      c('relationship_level', 'text'),
      c('current_location', 'text', { controlledList: 'location' }),
      c('current_activity', 'text'),
      c('last_seen_at', 'date'),
      c('mood', 'text'),
      c('known_words_count', 'integer'),
      c('deliveries_count', 'integer'),
      c('story_flags_json', 'json'),
      c('updated_at', 'date'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
];
