import type { TableTabDefinition } from '../types.js';
import { c } from './column-helper.js';

export const SYSTEM_CONFIG_TABS: TableTabDefinition[] = [
  {
    name: '01_APP_CONFIG',
    kind: 'table',
    purpose: 'Global editable application settings and active versions.',
    primaryKey: 'config_key',
    columns: [
      c('config_key', 'id'),
      c('value', 'text'),
      c('value_type', 'text'),
      c('description', 'text'),
      c('enabled', 'boolean'),
      c('restart_required', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '02_USERS',
    kind: 'table',
    purpose: 'Prototype user identities, roles, and plaintext access fields.',
    primaryKey: 'user_id',
    columns: [
      c('user_id', 'id'),
      c('display_name', 'text'),
      c('role', 'text', { controlledList: 'role' }),
      c('gate_code_plaintext', 'text', { sensitive: true }),
      c('admin_password_plaintext', 'text', { sensitive: true }),
      c('active', 'boolean'),
      c('default_language', 'text', { controlledList: 'locale' }),
      c('first_login_at', 'date'),
      c('last_login_at', 'date'),
      c('notes', 'text'),
    ],
    sensitivity: 'DEV_ONLY plaintext',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '03_SECRETS_DEV',
    kind: 'table',
    purpose:
      'Temporary plaintext Gemini, weather, and voice-provider credentials; backend access only.',
    primaryKey: 'secret_id',
    columns: [
      c('secret_id', 'id'),
      c('service_name', 'text'),
      c('key_name', 'text'),
      c('plaintext_value', 'text', { sensitive: true }),
      c('environment', 'text'),
      c('enabled', 'boolean'),
      c('last_updated_at', 'date'),
      c('notes', 'text'),
    ],
    sensitivity: 'DEV_ONLY plaintext',
    readBy: 'Backend only',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '04_ADMIN_FLAGS',
    kind: 'table',
    purpose: 'Live Admin switches and test overrides consumed without rebuilding React.',
    primaryKey: 'flag_id',
    columns: [
      c('flag_id', 'id'),
      c('scope', 'text'),
      c('target_user_id', 'id'),
      c('value', 'text'),
      c('value_type', 'text'),
      c('enabled', 'boolean'),
      c('updated_at', 'date'),
      c('updated_by', 'id'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '05_ENTRY_LOGS',
    kind: 'table',
    purpose: 'Append-only entry, authentication, navigation, completion, and IP audit events.',
    primaryKey: 'log_id',
    columns: [
      c('log_id', 'id'),
      c('timestamp', 'date'),
      c('user_id', 'id'),
      c('session_id', 'id'),
      c('event_type', 'text'),
      c('access_result', 'text'),
      c('ip_address', 'text', { sensitive: true }),
      c('user_agent', 'text'),
      c('device_id', 'id'),
      c('language', 'text', { controlledList: 'locale' }),
      c('route', 'text'),
      c('details_json', 'json'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '06_SESSIONS',
    kind: 'table',
    purpose: 'Current and historical Veoulla/Admin sessions.',
    primaryKey: 'session_id',
    columns: [
      c('session_id', 'id'),
      c('user_id', 'id'),
      c('created_at', 'date'),
      c('last_seen_at', 'date'),
      c('expires_at', 'date'),
      c('ip_address', 'text', { sensitive: true }),
      c('device_id', 'id'),
      c('status', 'text', { controlledList: 'session_status' }),
      c('gate_code_id', 'text'),
      c('current_location', 'text', { controlledList: 'location' }),
      c('current_story_beat', 'id'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
];
