import type { TableTabDefinition } from '../types.js';
import { c } from './column-helper.js';

export const VAR_TABS: TableTabDefinition[] = [
  {
    name: '40_VAR_CONVERSATIONS',
    kind: 'table',
    purpose: 'Append-only full VAR chat archive and Gemini interaction-chain metadata.',
    primaryKey: 'turn_id',
    columns: [
      c('turn_id', 'id'),
      c('conversation_id', 'id'),
      c('user_id', 'id'),
      c('session_id', 'id'),
      c('character_id', 'id'),
      c('sequence', 'integer'),
      c('speaker', 'text', { controlledList: 'var_speaker' }),
      c('locale', 'text', { controlledList: 'locale' }),
      c('message_text', 'text'),
      c('gemini_interaction_id', 'text', { sensitive: true }),
      c('previous_interaction_id', 'text', { sensitive: true }),
      c('created_at', 'date'),
      c('model_id', 'text'),
      c('input_tokens', 'integer'),
      c('output_tokens', 'integer'),
      c('status', 'text'),
      c('visible_to_player', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Private personal',
    readBy: 'Backend/Admin',
    writeBy: 'Backend',
    adminEditable: false,
    notes:
      'Keep every user/VAR turn; do not use as canonical world state. Not implemented before M15.',
  },
  {
    name: '41_VAR_MEMORIES',
    kind: 'table',
    purpose: 'Durable cross-session memories extracted from approved VAR conversations.',
    primaryKey: 'memory_id',
    columns: [
      c('memory_id', 'id'),
      c('user_id', 'id'),
      c('character_id', 'id'),
      c('category', 'text', { controlledList: 'memory_category' }),
      c('summary', 'text'),
      c('source_conversation_id', 'id'),
      c('importance', 'integer'),
      c('first_seen_at', 'date'),
      c('last_confirmed_at', 'date'),
      c('expires_at', 'date'),
      c('active', 'boolean'),
      c('admin_approved', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Private personal',
    readBy: 'Backend/Admin',
    writeBy: 'Backend/Admin',
    adminEditable: true,
    notes:
      'Used to reconstruct VAR context across sessions and model changes. Not implemented before M15.',
  },
];
