import type { TableTabDefinition } from '../types.js';
import { c } from './column-helper.js';

export const WORLD_STRUCTURE_TABS: TableTabDefinition[] = [
  {
    name: '11_LOCATIONS',
    kind: 'table',
    purpose: 'Canonical island locations and route/map metadata.',
    primaryKey: 'location_id',
    columns: [
      c('location_id', 'id', { controlledList: 'location' }),
      c('display_name_text_id', 'text'),
      c('subtitle_text_id', 'text'),
      c('map_order', 'integer'),
      c('road_side', 'text'),
      c('elevation_band', 'text'),
      c('first_visit_order', 'integer'),
      c('entry_scene_id', 'id'),
      c('key_type_id', 'id'),
      c('ambient_asset_id', 'id'),
      c('enabled', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '12_SCENES',
    kind: 'table',
    purpose: 'Scene packages, camera/movement profiles, transitions, and ambience.',
    primaryKey: 'scene_id',
    columns: [
      c('scene_id', 'id'),
      c('location_id', 'text', { controlledList: 'location' }),
      c('scene_type', 'text'),
      c('display_name', 'text'),
      c('background_asset_id', 'id'),
      c('mobile_asset_id', 'id'),
      c('entry_transition', 'text'),
      c('exit_transition', 'text'),
      c('camera_mode', 'text'),
      c('movement_profile', 'text'),
      c('ambient_audio_id', 'id'),
      c('enabled', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '13_ROUTES',
    kind: 'table',
    purpose: 'Story and event route definitions.',
    primaryKey: 'route_id',
    columns: [
      c('route_id', 'id'),
      c('route_name', 'text'),
      c('route_type', 'text'),
      c('start_scene_id', 'id'),
      c('end_scene_id', 'id'),
      c('mandatory_once', 'boolean'),
      c('allow_skip_after_complete', 'boolean'),
      c('active_version', 'text'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '14_STORY_BEATS',
    kind: 'table',
    purpose: 'Ordered, checkpointed story beats controlled entirely by Sheet data.',
    primaryKey: 'beat_id',
    columns: [
      c('beat_id', 'id'),
      c('route_id', 'id'),
      c('sequence', 'integer'),
      c('scene_id', 'id'),
      c('location_id', 'text', { controlledList: 'location' }),
      c('beat_type', 'text'),
      c('title_text_id', 'text'),
      c('dialogue_group_id', 'text'),
      c('voiceover_group_id', 'text'),
      c('required_interaction_id', 'text'),
      c('reward_rule_id', 'text'),
      c('checkpoint', 'boolean'),
      c('next_beat_id', 'id'),
      c('map_locked', 'boolean'),
      c('walkman_state', 'text'),
      c('enabled', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
  {
    name: '15_DIALOGUE',
    kind: 'table',
    purpose: 'Localized character dialogue and response behavior.',
    primaryKey: 'dialogue_row_id',
    columns: [
      c('dialogue_row_id', 'id'),
      c('dialogue_id', 'text'),
      c('group_id', 'text'),
      c('sequence', 'integer'),
      c('speaker_id', 'id'),
      c('locale', 'text', { controlledList: 'locale' }),
      c('text', 'text'),
      c('direction', 'text', { controlledList: 'direction' }),
      c('emotion', 'text'),
      c('display_mode', 'text'),
      c('voiceover_id', 'id'),
      c('requires_response', 'boolean'),
      c('response_type', 'text'),
      c('next_dialogue_id', 'text'),
      c('enabled', 'boolean'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
    notes:
      'dialogue_id/group_id repeat across locale rows; dialogue_row_id is the real primary key.',
  },
  {
    name: '16_VOICEOVER',
    kind: 'table',
    purpose: 'Five-language audio asset IDs, captions, direction, voice, and timing.',
    primaryKey: 'voiceover_id',
    columns: [
      c('voiceover_id', 'id'),
      c('content_type', 'text'),
      c('content_id', 'text'),
      c('locale', 'text', { controlledList: 'locale' }),
      c('audio_asset_id', 'id'),
      c('caption_text', 'text'),
      c('direction', 'text', { controlledList: 'direction' }),
      c('voice_name', 'text'),
      c('duration_ms', 'integer'),
      c('caption_start_ms', 'integer'),
      c('caption_end_ms', 'integer'),
      c('enabled', 'boolean'),
      c('notes', 'text'),
    ],
    sensitivity: 'Internal',
    readBy: 'React via backend',
    writeBy: 'Admin or backend',
    adminEditable: true,
  },
];
